"""Extract the user-model boundary record declarations VERBATIM from the
vendored dss_capi 0.14.5 Pascal source into `dss_capi_defs.inc`.

WASM_USERMODELS WP-WM.0 (P2): the ABI doc offset tables must be frozen from
FPC probe output over the *actual* vendored declarations, never from reading
or memory.  This script mechanically copies the declaration text (no editing,
no reflowing) so the probe (`abi_probe.pas`) and the P1 stub DLL
(`genstub.pas`) compile against byte-identical record definitions:

  - `Complex`/`pComplexArray` aliases  — src/Shared/DSSUcomplex.pas
  - `pIntegerArray`/`pDoubleArray` etc — src/Shared/ArrayDef.pas
  - `TGeneratorVars`                   — src/PCElements/generator.pas
  - `TDSSCallBacks`                    — src/Common/DSSCallBackRoutines.pas

`TDynamicsRec`/`TSolveMode` need no extraction: dss_capi's
src/Shared/Dynamics.pas is a standalone unit and the probes compile the real
unit directly (-Fu into the vendored tree).

Run:  python tools/fpc/usermodel_abi/extract_defs.py
"""
import hashlib
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parents[2]
SRC = ROOT / ".inputs" / "dss_capi" / "src"
OUT = HERE / "dss_capi_defs.inc"


def sha256(path: pathlib.Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def read_lines(path: pathlib.Path) -> list[str]:
    return path.read_text(encoding="utf-8", errors="strict").splitlines()


def pick_lines(path: pathlib.Path, needles: list[str]) -> list[str]:
    """Pick single lines, each matched by exactly one `needle in line` hit."""
    lines = read_lines(path)
    out = []
    for needle in needles:
        hits = [ln for ln in lines if needle in ln]
        if len(hits) != 1:
            sys.exit(f"FATAL: {path.name}: needle {needle!r} matched {len(hits)} lines")
        out.append(hits[0])
    return out


def pick_block(path: pathlib.Path, start_needle: str, end_trimmed: str = "end;") -> tuple[list[str], int, int]:
    """Pick the verbatim block from the unique line containing `start_needle`
    through the first following line whose trimmed text equals `end_trimmed`."""
    lines = read_lines(path)
    starts = [i for i, ln in enumerate(lines) if start_needle in ln]
    if len(starts) != 1:
        sys.exit(f"FATAL: {path.name}: start {start_needle!r} matched {len(starts)} lines")
    s = starts[0]
    for e in range(s + 1, len(lines)):
        if lines[e].strip() == end_trimmed:
            return lines[s : e + 1], s + 1, e + 1  # 1-based line numbers
    sys.exit(f"FATAL: {path.name}: no {end_trimmed!r} after line {s + 1}")


def main() -> None:
    ucx = SRC / "Shared" / "DSSUcomplex.pas"
    arr = SRC / "Shared" / "ArrayDef.pas"
    gen = SRC / "PCElements" / "generator.pas"
    cbk = SRC / "Common" / "DSSCallBackRoutines.pas"
    for p in (ucx, arr, gen, cbk):
        if not p.is_file():
            sys.exit(f"FATAL: vendored source missing: {p} — re-vendor .inputs/dss_capi, do not guess")

    ucx_lines = pick_lines(ucx, [
        "Complex = UComplex.Complex;",
        "pComplexArray = ^ComplexArray;",
        "ComplexArray = array [1..100] of Complex;",
    ])
    arr_lines = pick_lines(arr, [
        "pIntegerArray = ^LongIntArray;",
        "LongIntArray = array[1..100] of Longint;",
        "pDoubleArray = ^DoubleArray;",
        "DoubleArray = array[1..100] of Double;",
    ])
    gen_block, gs, ge = pick_block(gen, "TGeneratorVars = {$IFNDEF DSS_CAPI_NO_PACKED_RECORDS}packed{$ENDIF} record")
    cbk_block, cs, ce = pick_block(cbk, "pDSSCallBacks = ^TDSSCallBacks;")

    # The callback vtable is documented as 32 slots; assert we grabbed them all.
    import re
    slot_re = re.compile(r":\s+(Procedure|Function)\b", re.IGNORECASE)
    n_slots = sum(1 for ln in cbk_block if slot_re.search(ln))
    if n_slots != 32:
        sys.exit(f"FATAL: TDSSCallBacks slot count = {n_slots}, expected 32")

    body = []
    body.append("// AUTO-GENERATED by extract_defs.py — DO NOT EDIT BY HAND.")
    body.append("// Verbatim declarations from vendored dss_capi 0.14.5 (.inputs/dss_capi).")
    body.append("// Include inside a `type` section; requires `uses ucomplex` (FPC RTL).")
    body.append("")
    body.append(f"// --- src/Shared/DSSUcomplex.pas (sha256 {sha256(ucx)[:16]}...) ---")
    body.extend(ucx_lines)
    body.append("")
    body.append(f"// --- src/Shared/ArrayDef.pas (sha256 {sha256(arr)[:16]}...) ---")
    body.extend(arr_lines)
    body.append("")
    body.append(f"// --- src/PCElements/generator.pas lines {gs}-{ge} (sha256 {sha256(gen)[:16]}...) ---")
    body.extend(gen_block)
    body.append("")
    body.append(f"// --- src/Common/DSSCallBackRoutines.pas lines {cs}-{ce} (sha256 {sha256(cbk)[:16]}...) ---")
    body.extend(cbk_block)
    body.append("")

    OUT.write_text("\n".join(body) + "\n", encoding="utf-8", newline="\n")
    print(f"wrote {OUT} ({len(body)} lines); TGeneratorVars {gs}-{ge}, TDSSCallBacks {cs}-{ce}, 32 slots")


if __name__ == "__main__":
    main()
