"""Generate the feeders-controls-off gate artifacts (PHASE4_PLAN.md WP4.9;
historically "Phase 4").

For each IEEE test feeder (13/37/123 bus) this script:

1. Writes a **controls-off variant script** to
   `tests/golden/feeders_controlsoff/` — the master copied line by line with
   `solve`/`buscoords` lines dropped, top-level `redirect`/`compile` arguments
   rewritten relative to the variant's own directory (nested redirects inside
   the corpus need no rewriting because the current directory follows the
   redirect chain), and `Set controlmode=OFF` + `Solve` appended. Both engines
   compile **the same committed script**.
2. Compiles the variant with the pinned oracle (dss-python) and records the
   solution into `tests/golden/feeders_controlsoff.json`: convergence,
   iteration count, YNodeOrder, node voltages, total power, losses, and
   per-element powers/currents **as an ordered list** (the oracle's First/Next
   order is creation order; the Rust gate asserts on names too).

Usage:
    python tools/golden/gen_feeders_controlsoff.py

Regeneration is manual and must use the exact versions in tools/golden/PIN.txt.
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
TST_ROOT = REPO_ROOT / ".inputs" / "electricdss-tst" / "Version8" / "Distrib" / "IEEETestCases"
VARIANT_DIR = REPO_ROOT / "tests" / "golden" / "feeders_controlsoff"
OUT = REPO_ROOT / "tests" / "golden" / "feeders_controlsoff.json"
SCHEMA = 1

FEEDERS = [
    {"name": "ieee13", "dir": "13Bus", "master": "IEEE13Nodeckt.dss"},
    {"name": "ieee37", "dir": "37Bus", "master": "ieee37.dss"},
    {"name": "ieee123", "dir": "123Bus", "master": "IEEE123Master.dss"},
]


def check_pin() -> str:
    import dss

    pins = {}
    for line in (REPO_ROOT / "tools" / "golden" / "PIN.txt").read_text().splitlines():
        line = line.strip()
        if line and not line.startswith("#"):
            k, v = line.split("==")
            pins[k] = v
    if dss.__version__ != pins["dss-python"]:
        sys.exit(
            f"dss-python {dss.__version__} != pinned {pins['dss-python']}; "
            f"install the pinned version or update PIN.txt deliberately"
        )
    return dss.__version__


def make_variant(feeder: dict) -> Path:
    """Write the controls-off variant script; return its path."""
    case_dir = TST_ROOT / feeder["dir"]
    master = case_dir / feeder["master"]
    if not master.exists():
        sys.exit(f"master not found: {master}")

    # Path prefix from the variant's directory to the case directory,
    # computed (not hardcoded), with forward slashes for portability.
    rel = Path(os.path.relpath(case_dir, VARIANT_DIR)).as_posix()

    out_lines = [
        f"! Auto-generated by tools/golden/gen_feeders_controlsoff.py from "
        f"{master.relative_to(REPO_ROOT).as_posix()}\n",
        "! Controls-off variant: solve/buscoords dropped, redirect paths\n"
        "! rewritten relative to this directory, controlmode=OFF appended.\n",
        "! Regenerate manually with the pinned oracle (tools/golden/PIN.txt).\n",
        "\n",
    ]
    for line in master.read_text(encoding="latin-1").splitlines():
        tokens = line.strip().split(None, 1)
        first = tokens[0].lower() if tokens else ""
        if first in ("solve", "buscoords"):
            continue
        if first in ("redirect", "compile") and len(tokens) > 1:
            arg = tokens[1].split("!")[0].strip().strip('"')
            out_lines.append(f"{tokens[0]} {rel}/{arg}\n")
            continue
        out_lines.append(line + "\n")
    out_lines.append("\nSet controlmode=OFF\n")
    out_lines.append("Solve\n")

    VARIANT_DIR.mkdir(parents=True, exist_ok=True)
    variant = VARIANT_DIR / f"{feeder['name']}_controlsoff.dss"
    variant.write_text("".join(out_lines))
    return variant


def capture(d, variant: Path, name: str) -> dict:
    d.Text.Command = "clear"
    d.Text.Command = f'compile "{variant}"'

    ckt = d.ActiveCircuit
    sol = ckt.Solution
    varray = list(ckt.YNodeVarray)

    elements = []
    for full_name in ckt.AllElementNames:  # First/Next (creation) order
        ckt.SetActiveElement(full_name)
        el = ckt.ActiveCktElement
        elements.append(
            {
                "name": full_name,
                "powers": [float(x) for x in el.Powers],
                "currents": [float(x) for x in el.Currents],
            }
        )

    return {
        "name": name,
        "script": variant.relative_to(REPO_ROOT).as_posix(),
        "converged": bool(sol.Converged),
        "iterations": int(sol.Iterations),
        "node_order": list(ckt.YNodeOrder),
        "v_re": varray[0::2],
        "v_im": varray[1::2],
        "total_power": [float(x) for x in ckt.TotalPower],
        "losses": [float(x) for x in ckt.Losses],
        "elements": elements,
    }


def main() -> None:
    oracle_version = check_pin()
    from dss import dss as d

    scenarios = []
    for feeder in FEEDERS:
        variant = make_variant(feeder)
        sc = capture(d, variant, feeder["name"])
        scenarios.append(sc)
        print(
            f"{sc['name']}: {len(sc['node_order'])} nodes, "
            f"{len(sc['elements'])} elements, converged={sc['converged']}, "
            f"iterations={sc['iterations']}"
        )

    data = {
        "schema": SCHEMA,
        "oracle": {"dss_python": oracle_version, "engine": d.Version},
        "scenarios": scenarios,
    }
    OUT.write_text(json.dumps(data, indent=1))
    print(f"-> {OUT.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
