"""Generate the committed `midi_*` decks — the IEEE123-CLASS synthetic network
that carries the asymmetric-configuration and control/protection/metering
coverage of the micro gates (tests/corpus/asymmetric/, tests/corpus/controls/)
at a scale where LARGE-network failure modes exist. Micro decks cannot exercise
them; the vendored IEEE123/8500 corpus runs exercise the scale but not the
asymmetric element configs or the element-state channels. The midi network has:

  - >100 nodes (multi-digit node ordering, non-trivial sparse fill/ordering);
  - a 14-segment radial backbone (deep-chain voltage-drop accumulation);
  - a LOOP (two lateral ends tied) + a PARALLEL backbone segment (duplicate
    Y-stamp density — the insertion-order summation class);
  - 3 voltage levels (115 / 12.47 / 4.16+0.48) through cascaded transformers;
  - mixed 3ph/2ph/1ph laterals (the IEEE123 hallmark);
  - the asymmetric configs from the micro gates: Z1≠Z2 source + series
    reactor, FULL-asymmetric-input line/cap matrices, per-phase-unequal
    1-phase-bank taps, delta tertiary (with the proven physical common-mode pin);
  - (controls variant) cascaded regulators — LTC + a 3×1-phase bank — plus
    CapControls, InvControl, StorageController, meter/monitors: many controls
    acting in the same control iterations (queue tie-break ordering);
  - (protection variant) substation relay -> midline recloser -> lateral fuse
    coordination with the fault at the END of the deep lateral.

Deterministic (no randomness, no timestamps): rerunning reproduces the decks
byte-for-byte. The generated decks are COMMITTED artifacts; regenerate only
deliberately:

    python tools/decks/gen_midi_decks.py
"""

from __future__ import annotations

from pathlib import Path

REPO = Path(__file__).resolve().parents[2]

# ---------------------------------------------------------------------------
# Shared network body
# ---------------------------------------------------------------------------

HEADER = """\
// GENERATED by tools/decks/gen_midi_decks.py -- do not hand-edit; regenerate.
// The IEEE123-class midi network: see the generator docstring for the design
// rationale ({variant} variant).
clear
Set DefaultBaseFrequency=60
"""

LINECODES = """\
! FULL asymmetric matrix inputs (pin the ParseAsSymMatrix lower-triangle-wins
! overwrite order at scale).
new linecode.lca nphases=3 units=kft
~ rmatrix=[0.087 0.029 0.028 | 0.031 0.089 0.030 | 0.027 0.032 0.087]
~ xmatrix=[0.203 0.085 0.072 | 0.088 0.196 0.083 | 0.070 0.086 0.202]
~ cmatrix=[2.74 -0.70 -0.34 | -0.72 2.96 -0.71 | -0.33 -0.69 2.74]
new linecode.lcc nphases=3 units=kft
~ rmatrix=[0.095 0.033 0.025 | 0.036 0.098 0.034 | 0.028 0.037 0.094]
~ xmatrix=[0.215 0.092 0.078 | 0.096 0.208 0.090 | 0.075 0.093 0.212]
~ cmatrix=[2.55 -0.62 -0.30 | -0.66 2.80 -0.64 | -0.31 -0.60 2.52]
new linecode.lcb2 nphases=2 units=kft
~ rmatrix=[0.091 0.030 | 0.034 0.093]
~ xmatrix=[0.210 0.090 | 0.095 0.205]
~ cmatrix=[2.60 -0.60 | -0.65 2.55]
new linecode.lc1 nphases=1 r1=0.095 x1=0.21 c1=3.0 units=kft
"""

N_BACKBONE = 14  # segments bb1..bb15 (bb8->bb9 is the Z1<>Z2 series reactor)
REACTOR_SEG = 8  # bb8 -> bb9


def backbone(fixed_taps: bool) -> list[str]:
    """Substation + the 14-segment backbone with the mid-feeder 1-phase reg bank."""
    out = [
        "! Substation: Dy 115/12.47 (the LTC in the controls variant).",
        "new transformer.sub phases=3 windings=2 buses=(src, bb1) conns=(delta, wye)",
        "~ kvs=(115, 12.47) kvas=(20000, 20000) xhl=7"
        + (" taps=[1.0 1.0125]" if fixed_taps else ""),
    ]
    for i in range(1, N_BACKBONE + 1):
        a, b = f"bb{i}", f"bb{i + 1}"
        if i == REACTOR_SEG:
            out += [
                f"! Backbone segment {i}: the Z1<>Z2 series reactor (the",
                "! non-reciprocal-YPrim class of the 03c63f2 stamp bug) mid-chain.",
                f"new reactor.rser phases=3 bus1={a} bus2={b}",
                "~ Z1=[0.35 0.62] Z2=[0.08 0.21] Z0=[0.5 0.9]",
            ]
            continue
        code = "lcc" if i % 5 == 0 else "lca"
        length = [2, 3, 2, 4, 3, 2, 3, 0, 4, 2, 3, 2, 3, 2][i - 1]
        out.append(
            f"new line.bb{i}_{i + 1} bus1={a} bus2={b} linecode={code} "
            f"length={length} units=kft"
        )
    out += [
        "! Parallel line on segment 5 (duplicate stamps on the same node pair).",
        "new line.bb5_6p bus1=bb5 bus2=bb6 linecode=lcc length=4 units=kft",
        "",
        "! Mid-feeder 1-phase regulating bank bb10 -> rb (per-phase-unequal",
        "! FIXED taps in the asym variant; RegControls in the controls variant).",
    ]
    bank_taps = ["1.025", "0.9875", "1.05"] if fixed_taps else ["1.0", "1.0", "1.0"]
    for ph, tap in zip((1, 2, 3), bank_taps):
        out += [
            f"new transformer.rbank{ph} phases=1 windings=2 "
            f"buses=(bb10.{ph}, rb.{ph}) conns=(wye, wye)",
            f"~ kvs=(7.2, 7.2) kvas=(2500, 2500) xhl=1 taps=[1.0 {tap}]",
        ]
    out += [
        "! The backbone continues from the regulated bus.",
        "new line.rb_bb11 bus1=rb bus2=bb11 linecode=lca length=2 units=kft",
    ]
    return out


def laterals() -> list[str]:
    out = [
        "",
        "! --- Laterals: mixed 3ph/2ph/1ph, a loop, cascaded voltage levels ---",
        "! L1 @bb2: 3-phase, 2 segments.",
        "new line.l1a bus1=bb2 bus2=l1m linecode=lca length=3 units=kft",
        "new line.l1b bus1=l1m bus2=l1e linecode=lcc length=2 units=kft",
        "! L2 @bb3: 1-phase (phase 2), 2 segments.",
        "new line.l2a phases=1 bus1=bb3.2 bus2=l2m.2 linecode=lc1 length=2 units=kft",
        "new line.l2b phases=1 bus1=l2m.2 bus2=l2e.2 linecode=lc1 length=2 units=kft",
        "! L3 @bb4: 2-phase (phases 1,3), 2 segments.",
        "new line.l3a phases=2 bus1=bb4.1.3 bus2=l3m.1.3 linecode=lcb2 length=2 units=kft",
        "new line.l3b phases=2 bus1=l3m.1.3 bus2=l3e.1.3 linecode=lcb2 length=2 units=kft",
        "! L4 @bb5: 3-phase, 3 segments (loops to L6's end below).",
        "new line.l4a bus1=bb5 bus2=l4m linecode=lca length=3 units=kft",
        "new line.l4b bus1=l4m bus2=l4n linecode=lca length=2 units=kft",
        "new line.l4c bus1=l4n bus2=l4e linecode=lcc length=2 units=kft",
        "! L5 @bb7: 1-phase (phase 1) + a 1-phase service transformer spur.",
        "new line.l5a phases=1 bus1=bb7.1 bus2=l5m.1 linecode=lc1 length=2 units=kft",
        "new transformer.t5 phases=1 windings=2 buses=(l5m.1, l5lv.1) conns=(wye, wye)",
        "~ kvs=(7.2, 0.277) kvas=(167, 167) xhl=2.3",
        "! L6 @bb12: 3-phase, 3 segments; its end ties back to L4's end -> LOOP.",
        "new line.l6a bus1=bb12 bus2=l6m linecode=lca length=3 units=kft",
        "new line.l6b bus1=l6m bus2=l6n linecode=lcc length=2 units=kft",
        "new line.l6c bus1=l6n bus2=l6e linecode=lca length=2 units=kft",
        "new line.tie bus1=l4e bus2=l6e switch=yes",
        "! L7 @bb13: 2-phase (phases 2,3).",
        "new line.l7a phases=2 bus1=bb13.2.3 bus2=l7e.2.3 linecode=lcb2 length=3 units=kft",
        "! L8 @bb14: 3-winding step-down 12.47/4.16/0.48 (delta tertiary; the",
        "! tertiary bus is pinned physically — the proven ppm-antifloat",
        "! common-mode floor, never a tolerance dodge).",
        "new transformer.t8 phases=3 windings=3 buses=(bb14, l8mv, l8lv)",
        "~ conns=(wye, delta, wye) kvs=(12.47, 0.48, 4.16) kvas=(5000, 3000, 2000)",
        "~ xhl=6 xht=5 xlt=3",
        "new capacitor.cpin8 phases=3 bus1=l8mv conn=wye kvar=25 kv=0.48",
        "! L9 @bb15 (feeder end): the DER pocket.",
        "new line.l9a bus1=bb15 bus2=l9e linecode=lca length=2 units=kft",
    ]
    return out


def shunts_and_der(include_indmach: bool) -> list[str]:
    out = [
        "",
        "! --- Shunt asymmetries ---",
        "! FULL asymmetric cmatrix bank at bb6.",
        "new capacitor.cmat phases=3 bus1=bb6",
        "~ cmatrix=[3.2 -0.9 -0.3 | -0.5 3.5 -0.7 | -0.4 -1.1 3.1]",
        "! Delta bank at bb13.",
        "new capacitor.cdel phases=3 bus1=bb13 conn=delta kvar=300 kv=12.47",
        "! 1-phase shunt reactor on bb4 phase 3.",
        "new reactor.rsh phases=1 bus1=bb4.3 kvar=120 kv=7.2",
        "",
        "! --- DER pocket at the feeder end ---",
        "new pvsystem.pv3 phases=3 bus1=l9e conn=delta kv=12.47 kva=600 pmpp=500",
        "~ irradiance=0.9 pf=0.98",
        "new pvsystem.pv1 phases=1 bus1=l6m.2 kv=7.2 kva=150 pmpp=120 irradiance=0.85 pf=1",
        "new storage.st1 phases=3 bus1=l9e kv=12.47 kwrated=400 kva=400 kwhrated=1600",
        "~ %stored=75 %idlingkw=0 pf=1.0",
        "new generator.g1 phases=3 bus1=l4m conn=wye model=1 kv=12.47 kw=500 pf=0.95",
        "~ vminpu=0.8",
    ]
    if include_indmach:
        out += [
            "! Induction machine behind its own Dy at the 0.48 winding of t8.",
            "new capacitor.cg conn=wye bus1=l8mv phases=3 kvar=300 kv=0.48",
            "new indmach012.m1 bus1=l8mv kv=0.48 kw=800 conn=delta kva=1000 h=6",
            "~ purs=0.048 puxs=0.075 purr=0.018 puxr=0.12 puxm=3.8 slip=0.02",
            "~ slipoption=variableslip",
        ]
    return out


# (bus, phases-spec, conn, model, kv, kw, pf, extra)
LOADS = [
    ("l1e.1", 1, "wye", 1, 7.2, 260, 0.90, ""),
    ("l1e.2", 1, "wye", 2, 7.2, 90, 0.95, ""),
    ("l1e.3", 1, "wye", 5, 7.2, 340, 0.85, ""),
    ("l1m", 3, "delta", 2, 12.47, 240, 0.92, ""),
    ("l2e.2", 1, "wye", 1, 7.2, 210, 0.90, ""),
    ("l3e.1", 1, "wye", 1, 7.2, 180, 0.92, ""),
    ("l3e.3", 1, "wye", 5, 7.2, 260, 0.88, ""),
    ("l4m.1", 1, "wye", 1, 7.2, 300, 0.90, ""),
    ("l4n.2", 1, "wye", 2, 7.2, 110, 0.95, ""),
    ("l4e.3", 1, "wye", 1, 7.2, 330, 0.87, ""),
    ("l5lv.1", 1, "wye", 1, 0.277, 95, 0.92, ""),
    ("l6m.1", 1, "wye", 1, 7.2, 280, 0.90, ""),
    ("l6n.3", 1, "wye", 5, 7.2, 310, 0.86, ""),
    ("l6e", 3, "wye", 8, 12.47, 330, 0.93, " zipv=[0.4 0.3 0.3 0.5 0.3 0.2 0.6]"),
    ("l7e.2", 1, "wye", 1, 7.2, 190, 0.91, ""),
    ("l7e.3", 1, "wye", 2, 7.2, 240, 0.89, ""),
    ("l8mv", 3, "delta", 1, 0.48, 420, 0.90, ""),
    ("l8lv.1", 1, "wye", 1, 2.4, 170, 0.92, ""),
    ("l8lv.3", 1, "wye", 1, 2.4, 120, 0.88, ""),
    ("l9e.1", 1, "wye", 1, 7.2, 350, 0.90, ""),
    ("l9e.2", 1, "wye", 1, 7.2, 130, 0.95, ""),
    ("l9e.3", 1, "wye", 5, 7.2, 420, 0.85, ""),
    ("bb6", 3, "wye", 3, 12.47, 280, 0.94, ""),
    ("bb11.2", 1, "wye", 1, 7.2, 160, 0.93, ""),
]


def loads(daily: bool) -> list[str]:
    out = ["", "! --- Per-phase-unequal loads, mixed models 1/2/3/5/8 ---"]
    tail = " daily=day" if daily else ""
    for i, (bus, ph, conn, model, kv, kw, pf, extra) in enumerate(LOADS, 1):
        out.append(
            f"new load.ld{i} bus1={bus} phases={ph} conn={conn} model={model} "
            f"kv={kv} kw={kw} pf={pf} vminpu=0.85{extra}{tail}"
        )
    return out


FOOTER = """\

set voltagebases=[115 12.47 4.16 0.48]
calcvoltagebases
"""


def deck_midi_asym() -> str:
    parts = [
        HEADER.format(variant="asymmetric-snapshot"),
        "! Z1<>Z2 source (asymmetric source YPrim).",
        "new circuit.midi basekv=115 pu=1.02 angle=0 phases=3 bus1=src",
        "~ Z1=[0.9 3.6] Z2=[0.55 2.1] Z0=[2.1 6.6]",
        "",
        LINECODES,
        *backbone(fixed_taps=True),
        *laterals(),
        *shunts_and_der(include_indmach=True),
        *loads(daily=False),
        FOOTER,
        "Set maxiterations=100",
    ]
    return "\n".join(parts) + "\n"


CONTROLS_EXTRA = """\

! --- The control layer (cascaded regulators + caps + DER controls) ---
new regcontrol.ltc transformer=sub winding=2 vreg=123 band=2 ptratio=60
~ eventlog=yes
new regcontrol.rga transformer=rbank1 winding=2 vreg=119 band=2 ptratio=60
~ eventlog=yes
new regcontrol.rgb transformer=rbank2 winding=2 vreg=119 band=2 ptratio=60
~ eventlog=yes
new regcontrol.rgc transformer=rbank3 winding=2 vreg=119 band=2 ptratio=60
~ eventlog=yes
! kvar-mode CapControls: voltage mode under two cascaded regulators hunts
! (the LTC/bank mask the excursions -- the combo_voltvar_asym lesson). The
! ON/OFF deadband must exceed the bank's own kvar (600 for cdel), else the
! control hunts when the load kvar lands inside the bank-sized window.
new capcontrol.ccv element=line.bb1_2 terminal=1 capacitor=cmat type=kvar
~ onsetting=2000 offsetting=1150 eventlog=yes
new capcontrol.cck element=line.bb12_13 terminal=1 capacitor=cdel type=kvar
~ onsetting=450 offsetting=150 eventlog=yes
new xycurve.vv npts=5 yarray=(1 1 0 -1 -1) xarray=(0.5 0.92 1.0 1.08 1.5)
new invcontrol.ic mode=VOLTVAR voltage_curvex_ref=rated vvc_curve1=vv
~ deltaq_factor=0.2 refreactivepower=VARMAX
new storagecontroller.sc element=line.bb1_2 terminal=1 modedis=peakshave
~ monphase=avg kwtarget=4300 %reserve=20 eventlog=yes

! --- Metering layer ---
new energymeter.em element=transformer.sub terminal=1
new monitor.m0 element=line.bb5_6 terminal=1 mode=0
new monitor.m2 element=transformer.rbank1 terminal=2 mode=2
new monitor.m3 element=storage.st1 terminal=1 mode=3
new sensor.sn element=line.bb1_2 terminal=1 kvbase=7.2 conn=wye
~ currents=[250 180 300]

new loadshape.day npts=24 interval=1
~ mult=(0.35 0.37 0.40 0.45 0.52 0.60 0.70 0.80 0.87 0.92 0.95 0.94 0.90 0.85 0.80 0.75 0.70 0.72 0.80 0.88 0.92 0.75 0.55 0.40)
"""


def deck_midi_controls() -> str:
    parts = [
        HEADER.format(variant="controls-daily"),
        "new circuit.midi basekv=115 pu=1.03 angle=0 phases=3 bus1=src",
        "~ mvasc3=15000 mvasc1=12000",
        "",
        LINECODES,
        *backbone(fixed_taps=False),
        *laterals(),
        *shunts_and_der(include_indmach=False),
        CONTROLS_EXTRA,
        *loads(daily=True),
        FOOTER,
        "Set maxcontroliter=2000",
        "Set maxiterations=100",
        "Set mode=daily stepsize=1h number=1",
    ]
    return "\n".join(parts) + "\n"


PROTECTION_EXTRA = """\

! --- The protection layer (coordination through the chain depth) ---
! Substation backup relay (slow definite-time OC).
new relay.backup type=current monitoredobj=transformer.sub monitoredterm=2
~ switchedobj=transformer.sub switchedterm=2 phasetrip=900 groundtrip=450
~ delay=1.5 shots=1 recloseintervals=None eventlog=yes
! Midline recloser on backbone segment 11->12 (upstream of L6).
new recloser.r monitoredobj=line.bb11_12 monitoredterm=1
~ switchedobj=line.bb11_12 switchedterm=1 numfast=1 shots=3
~ phasetrip=150 groundtrip=75 recloseintervals=(0.5, 1.0)
! Lateral fuse at the head of L6.
new fuse.fz monitoredobj=line.l6a monitoredterm=1
~ switchedobj=line.l6a switchedterm=1 ratedcurrent=50
! Permanent SLG fault at the very END of the deep lateral (phase 1).
new fault.f bus1=l6e.1 phases=1 ontime=0.2 r=0.5 temporary=no

new energymeter.em element=transformer.sub terminal=1
new monitor.mm element=line.bb11_12 terminal=1 mode=0
"""


def deck_midi_protection() -> str:
    parts = [
        HEADER.format(variant="protection-duty"),
        "new circuit.midi basekv=115 pu=1.02 angle=0 phases=3 bus1=src",
        "~ mvasc3=20000 mvasc1=21000",
        "",
        LINECODES,
        *backbone(fixed_taps=True),
        # Radial for deterministic coordination: the loop tie stays open.
        *[
            ln.replace("switch=yes", "switch=yes enabled=no")
            for ln in laterals()
        ],
        *shunts_and_der(include_indmach=False),
        PROTECTION_EXTRA,
        *loads(daily=False),
        FOOTER,
        "Set maxiterations=100",
        "set mode=duty stepsize=0.1 number=1 controlmode=time",
    ]
    return "\n".join(parts) + "\n"


def main() -> None:
    targets = {
        REPO / "tests" / "corpus" / "asymmetric" / "midi_asym.dss": deck_midi_asym(),
        REPO / "tests" / "corpus" / "controls" / "midi_controls.dss": deck_midi_controls(),
        REPO / "tests" / "corpus" / "controls" / "midi_protection.dss": deck_midi_protection(),
    }
    for path, text in targets.items():
        path.write_text(text, encoding="utf-8", newline="\n")
        print(f"wrote {path.relative_to(REPO)} ({len(text.splitlines())} lines)")


if __name__ == "__main__":
    main()
