"""Vendor the `electricdss-tst` corpus into the repository (CORPUS_TEST_PLAN.md §1).

Copies `.inputs/electricdss-tst` -> `tests/corpus/electricdss-tst` **verbatim**,
preserving every relative path so the copy is self-contained (the engine resolves
`redirect`/`compile` relative to each master's directory, so no path rewrites are
needed). The committed copy is what the live corpus gate (`corpus_live.rs`) reads
at test time — `.inputs` is temporary and must not be a runtime dependency.

Exclusions (the ONLY things not copied):
  - the corpus's own VCS metadata `.git/` (not corpus content);
  - whatever the corpus's own `.gitignore` excludes (currently `*.pickle.*`).

Also writes:
  - `tests/corpus/README.md`  — provenance (source commit, date, counts, rules);
  - `tests/corpus/SHA256SUMS`  — checksum of every copied file (re-vendor / drift
    detection); verifiable from `tests/corpus/` with `sha256sum -c SHA256SUMS`.

Run once (and again only to re-vendor):
    python tools/corpus/vendor.py            # refuses if the dest exists
    python tools/corpus/vendor.py --force     # wipe + recopy
"""

from __future__ import annotations

import fnmatch
import hashlib
import shutil
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
SRC = REPO_ROOT / ".inputs" / "electricdss-tst"
CORPUS_DIR = REPO_ROOT / "tests" / "corpus"
DST = CORPUS_DIR / "electricdss-tst"


def load_gitignore_patterns(root: Path) -> list[str]:
    """Simple `.gitignore` patterns (non-empty, non-comment lines)."""
    gi = root / ".gitignore"
    if not gi.is_file():
        return []
    pats = []
    for line in gi.read_text().splitlines():
        line = line.strip()
        if line and not line.startswith("#"):
            pats.append(line)
    return pats


def is_ignored(rel_posix: str, name: str, patterns: list[str]) -> bool:
    """Match a relative posix path / basename against simple gitignore globs."""
    for pat in patterns:
        p = pat.rstrip("/")
        if fnmatch.fnmatch(name, p) or fnmatch.fnmatch(rel_posix, p):
            return True
    return False


def source_commit() -> str:
    try:
        out = subprocess.run(
            ["git", "-C", str(SRC), "rev-parse", "HEAD"],
            capture_output=True,
            text=True,
            check=True,
        )
        return out.stdout.strip()
    except Exception as e:  # noqa: BLE001
        return f"<unknown: {e}>"


def main() -> None:
    force = "--force" in sys.argv[1:]
    if not SRC.is_dir():
        sys.exit(f"source corpus not found: {SRC}")
    if DST.exists() and any(DST.iterdir()) and not force:
        sys.exit(f"destination already exists: {DST}\n  re-run with --force to re-sync")

    patterns = load_gitignore_patterns(SRC)
    print(f"source     : {SRC}")
    print(f"destination: {DST}")
    print(f"exclusions : .git/ + gitignore {patterns}")

    # Copy every source file (overwriting), tracking the exact source set. We do
    # NOT rmtree the destination first: running a case in-place can leave the
    # tree with a locked dir (AV/indexer) and outputs, so we re-sync file-by-file
    # and prune extras afterward — robust to locks.
    copied: list[tuple[str, int]] = []  # (rel_posix under electricdss-tst, size)
    copied_rel: set[str] = set()
    skipped_ignored = 0
    for path in sorted(SRC.rglob("*")):
        # Prune the corpus's own VCS metadata.
        parts = path.relative_to(SRC).parts
        if ".git" in parts:
            continue
        rel = path.relative_to(SRC)
        rel_posix = rel.as_posix()
        if path.is_dir():
            continue
        if is_ignored(rel_posix, path.name, patterns):
            skipped_ignored += 1
            continue
        out = DST / rel
        out.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(path, out)
        copied.append((rel_posix, path.stat().st_size))
        copied_rel.add(rel_posix)

    # Prune anything in the destination not part of the source set — stale files
    # or outputs generated by running cases in-place (e.g. LineConstantsCode.dss,
    # EnergyMeter DI_*.csv) — so the copy is an exact mirror of the source.
    pruned = 0
    for p in sorted(DST.rglob("*"), reverse=True):
        if p.is_file() and p.relative_to(DST).as_posix() not in copied_rel:
            try:
                p.unlink()
                pruned += 1
            except OSError as e:  # noqa: PERF203
                print(f"  warn: could not prune {p}: {e}")
        elif p.is_dir():
            try:
                p.rmdir()  # only succeeds if now empty
            except OSError:
                pass

    # SHA256SUMS over every copied file, paths relative to tests/corpus/ so the
    # file verifies with `sha256sum -c` run from tests/corpus/.
    lines = []
    for rel_posix, _ in copied:
        digest = hashlib.sha256((DST / rel_posix).read_bytes()).hexdigest()
        lines.append(f"{digest}  electricdss-tst/{rel_posix}")
    CORPUS_DIR.mkdir(parents=True, exist_ok=True)
    (CORPUS_DIR / "SHA256SUMS").write_text("\n".join(lines) + "\n")

    total_bytes = sum(sz for _, sz in copied)
    n_dss = sum(1 for rel, _ in copied if rel.lower().endswith(".dss"))
    readme = f"""# Vendored `electricdss-tst` corpus

Verbatim copy of the OpenDSS test corpus, used by the live oracle-comparison gate
(`crates/dss-core/tests/corpus_live.rs`) and as the in-repo replacement for the
temporary `.inputs/electricdss-tst`. See `CORPUS_TEST_PLAN.md`.

**Do not edit these files by hand.** Re-vendor with `python tools/corpus/vendor.py
--force` and review the `SHA256SUMS` diff.

**Note:** running the live gate (`DSS_LIVE_ORACLE=1`) or the classifier
(`DSS_LIVE_CLASSIFY=1`) executes cases *in place*, so OpenDSS writes outputs
(EnergyMeter `DI_*.csv`, exports, `LineConstantsCode.dss`, …) into this tree.
Re-run `python tools/corpus/vendor.py --force` (it copies the source and prunes
any extra files) to restore the pristine mirror before committing or before
running the always-on `corpus_manifest` gate.

| field | value |
|---|---|
| source | `.inputs/electricdss-tst` |
| source commit | `{source_commit()}` |
| vendored (UTC) | {datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S")} |
| files copied | {len(copied)} |
| of which `.dss` | {n_dss} |
| total size | {total_bytes / 1024 / 1024:.1f} MiB |
| excluded | `.git/`, gitignore `{patterns}` ({skipped_ignored} files) |

Relative paths are preserved exactly, so masters resolve their `redirect`/
`compile` data dependencies internally with no path rewrites. `SHA256SUMS` lists
every copied file (paths relative to `tests/corpus/`); verify with
`sha256sum -c SHA256SUMS` from this directory.

Every `.dss` file here is accounted for in exactly one manifest under
`tests/corpus/manifests/` — enforced by `corpus_manifest.rs`.
"""
    (CORPUS_DIR / "README.md").write_text(readme)

    print(
        f"copied {len(copied)} files ({total_bytes / 1024 / 1024:.1f} MiB), "
        f"{n_dss} .dss; pruned {pruned} extra; skipped {skipped_ignored} ignored; "
        f"wrote README.md + SHA256SUMS"
    )


if __name__ == "__main__":
    main()
