//! Native-twin parity pin (WP-WM.2 item 3/4 pre-stage): replays the exact
//! `tools/wasm_usermodel/twin_probe.py` scenario against the Rust port
//! (`mainunit` level — the same functions the wasm exports shim into) and
//! asserts every recorded value BIT-EXACT against the FPC-built native twin
//! (expected values generated by `twin_probe.py --rust`, evidence copy
//! `docs/wasm/probes/p6_twin_expected.txt`).
//!
//! The model uses only f64 `+ - * /` / `sqrt` (IEEE-exact on x86-64 SSE2 and
//! in wasm), so the floor is exact bit equality — any mismatch is a port bug,
//! never "tolerance". The integrator (WM.2 item 4) re-pins the committed
//! `.wasm` against the same constants through the `dss-usermodel` crate API.
//!
//! Run: `cargo +stable test` in `tools/wasm_usermodel/models/indmach012a`
//! (host target; the crate is workspace-excluded so the repo gate does not
//! run it — the committed artifact is gated via WM.1/WM.3).
//!
//! ABI re-freeze to r4133 (user decision 2026-07-19): the native twin is now
//! the r4133 build (`build_native.ps1`). Its `TGeneratorVars` grew the
//! r4088+/NCIM `deltaQNom` slot (244->252 B, native side only). Because the
//! IndMach012a model math is byte-identical r3723->r4133 and `deltaQNom` never
//! reaches the model, EVERY value in `twin_expected.rs` is bit-identical to the
//! r3723 image (re-derived + diffed; evidence `p8_twin_r4133_bridge.txt` +
//! `p8_indmach012a_math_diff.txt`). The **wasm-side** record round-tripped by
//! `record_codec_round_trip` below stays the compact 244-B image (NumPhases@176,
//! VthevMag@188) — `deltaQNom` is host-managed and never crosses the boundary,
//! so the wasm layout is unchanged (ABI doc §2.2).

#[allow(dead_code)]
mod expected {
    include!("twin_expected.rs");
}

use indmach012a::cmath::{cmplx, Complex, CZERO};
use indmach012a::mainunit::{self, MainState};
use indmach012a::records::{DynamicsRec, GeneratorVars, DYNAMICMODE};

// The fixed scenario inputs — duplicated verbatim from twin_probe.py.
const W0: f64 = 376.99111843077515; // 2*pi*60, fixed literal on both sides
const V_PF: [Complex; 3] = [
    Complex {
        re: 277.13,
        im: 0.0,
    },
    Complex {
        re: -140.02,
        im: -239.51,
    },
    Complex {
        re: -137.11,
        im: 240.05,
    },
];
const V_DYN: [Complex; 3] = [
    Complex { re: 276.4, im: 3.1 },
    Complex {
        re: -141.0,
        im: -238.2,
    },
    Complex {
        re: -135.9,
        im: 239.9,
    },
];
const EDIT_STR: &[u8] =
    b"rs=0.048 xs=0.075 rr=0.018 xr=0.12 Xm=3.8 maxs=0.1 option=variableslip slip=-0.02";
const H_DYN: f64 = 0.0002;

#[track_caller]
fn assert_bits(what: &str, got: f64, expected_bits: u64) {
    assert_eq!(
        got.to_bits(),
        expected_bits,
        "{what}: got {got:?} (0x{:016X}), twin has {:?} (0x{expected_bits:016X})",
        got.to_bits(),
        f64::from_bits(expected_bits),
    );
}

fn vars(state: &MainState) -> [f64; 14] {
    let mut out = [0.0; 14];
    for (i, slot) in out.iter_mut().enumerate() {
        *slot = mainunit::get_variable(state, (i + 1) as i32);
    }
    out
}

#[track_caller]
fn assert_vars(prefix: &str, got: &[f64; 14], expected: &[u64; 14]) {
    for (i, (g, e)) in got.iter().zip(expected).enumerate() {
        assert_bits(&format!("{prefix}_{}", i + 1), *g, *e);
    }
}

#[test]
fn twin_parity_scenario() {
    use expected as e;

    let mut state = MainState::new();

    let mut gen = GeneratorVars {
        w0: W0,
        hmass: 6.0,
        kva_rating: 1500.0,
        kv_generator_base: 0.48,
        pnominal_per_phase: 400000.0,
        qnominal_per_phase: 145000.0,
        num_phases: 3,
        num_conductors: 3,
        conn: 1,
        ..Default::default()
    };
    let mut dyn_rec = DynamicsRec {
        h: 0.001,
        tstop: 1.0,
        solution_mode: 0, // SNAPSHOT
        ..Default::default()
    };

    // S1: New
    let id = mainunit::new_instance(&mut state, &mut gen, 0, 0);
    assert_eq!(id, e::NEW_ID);
    assert_bits("after_new_speed", gen.speed, e::AFTER_NEW_SPEED);

    // S2: variable-name surface
    assert_eq!(mainunit::num_vars(), e::NUM_VARS);
    let expected_names: [&str; 14] = [
        e::VAR_NAME_1,
        e::VAR_NAME_2,
        e::VAR_NAME_3,
        e::VAR_NAME_4,
        e::VAR_NAME_5,
        e::VAR_NAME_6,
        e::VAR_NAME_7,
        e::VAR_NAME_8,
        e::VAR_NAME_9,
        e::VAR_NAME_10,
        e::VAR_NAME_11,
        e::VAR_NAME_12,
        e::VAR_NAME_13,
        e::VAR_NAME_14,
    ];
    for (i, want) in expected_names.iter().enumerate() {
        let bytes = mainunit::get_var_name((i + 1) as i32, 32).unwrap();
        let name = std::str::from_utf8(&bytes[..bytes.len() - 1]).unwrap();
        assert_eq!(name, *want, "var_name_{}", i + 1);
        assert_eq!(*bytes.last().unwrap(), 0, "NUL terminator");
    }
    // StrLCopy truncation at maxlen=4
    let bytes = mainunit::get_var_name(12, 4).unwrap();
    assert_eq!(&bytes, b"Stat\0", "var_name_12_maxlen4");
    assert_eq!(
        std::str::from_utf8(&bytes[..4]).unwrap(),
        e::VAR_NAME_12_MAXLEN4
    );
    // Out-of-range VarNum: buffer untouched
    assert!(mainunit::get_var_name(15, 8).is_none());
    assert_eq!(e::VAR_NAME_15_UNTOUCHED, "yes");

    // S3: initial variables (post-Create state)
    assert_vars(
        "vars_initial",
        &vars(&state),
        &[
            e::VARS_INITIAL_1,
            e::VARS_INITIAL_2,
            e::VARS_INITIAL_3,
            e::VARS_INITIAL_4,
            e::VARS_INITIAL_5,
            e::VARS_INITIAL_6,
            e::VARS_INITIAL_7,
            e::VARS_INITIAL_8,
            e::VARS_INITIAL_9,
            e::VARS_INITIAL_10,
            e::VARS_INITIAL_11,
            e::VARS_INITIAL_12,
            e::VARS_INITIAL_13,
            e::VARS_INITIAL_14,
        ],
    );

    // S4: Edit
    let mut msgs: Vec<Vec<u8>> = Vec::new();
    let mut sink = |b: &[u8]| msgs.push(b.to_vec());
    mainunit::edit(&mut state, EDIT_STR, &mut gen, &mut sink);
    assert_bits("after_edit_speed", gen.speed, e::AFTER_EDIT_SPEED);
    assert_vars(
        "vars_after_edit",
        &vars(&state),
        &[
            e::VARS_AFTER_EDIT_1,
            e::VARS_AFTER_EDIT_2,
            e::VARS_AFTER_EDIT_3,
            e::VARS_AFTER_EDIT_4,
            e::VARS_AFTER_EDIT_5,
            e::VARS_AFTER_EDIT_6,
            e::VARS_AFTER_EDIT_7,
            e::VARS_AFTER_EDIT_8,
            e::VARS_AFTER_EDIT_9,
            e::VARS_AFTER_EDIT_10,
            e::VARS_AFTER_EDIT_11,
            e::VARS_AFTER_EDIT_12,
            e::VARS_AFTER_EDIT_13,
            e::VARS_AFTER_EDIT_14,
        ],
    );

    // S5: five power-flow Calc iterations at fixed V (slip fixed-point)
    let pf_i_expected: [[u64; 6]; 5] = [
        [
            e::PF_I_1_0,
            e::PF_I_1_1,
            e::PF_I_1_2,
            e::PF_I_1_3,
            e::PF_I_1_4,
            e::PF_I_1_5,
        ],
        [
            e::PF_I_2_0,
            e::PF_I_2_1,
            e::PF_I_2_2,
            e::PF_I_2_3,
            e::PF_I_2_4,
            e::PF_I_2_5,
        ],
        [
            e::PF_I_3_0,
            e::PF_I_3_1,
            e::PF_I_3_2,
            e::PF_I_3_3,
            e::PF_I_3_4,
            e::PF_I_3_5,
        ],
        [
            e::PF_I_4_0,
            e::PF_I_4_1,
            e::PF_I_4_2,
            e::PF_I_4_3,
            e::PF_I_4_4,
            e::PF_I_4_5,
        ],
        [
            e::PF_I_5_0,
            e::PF_I_5_1,
            e::PF_I_5_2,
            e::PF_I_5_3,
            e::PF_I_5_4,
            e::PF_I_5_5,
        ],
    ];
    let pf_slip_expected = [
        e::PF_SLIP_1,
        e::PF_SLIP_2,
        e::PF_SLIP_3,
        e::PF_SLIP_4,
        e::PF_SLIP_5,
    ];
    let mut i_out = [CZERO; 3];
    for it in 0..5 {
        let wrote = mainunit::calc(&mut state, &V_PF, &mut i_out, &mut gen, &dyn_rec);
        assert!(wrote);
        for k in 0..3 {
            assert_bits(
                &format!("pf_i_{}_{}", it + 1, 2 * k),
                i_out[k].re,
                pf_i_expected[it][2 * k],
            );
            assert_bits(
                &format!("pf_i_{}_{}", it + 1, 2 * k + 1),
                i_out[k].im,
                pf_i_expected[it][2 * k + 1],
            );
        }
        assert_bits(
            &format!("pf_slip_{}", it + 1),
            mainunit::get_variable(&state, 1),
            pf_slip_expected[it],
        );
    }

    // S6: variables after power flow
    assert_vars(
        "vars_after_pflow",
        &vars(&state),
        &[
            e::VARS_AFTER_PFLOW_1,
            e::VARS_AFTER_PFLOW_2,
            e::VARS_AFTER_PFLOW_3,
            e::VARS_AFTER_PFLOW_4,
            e::VARS_AFTER_PFLOW_5,
            e::VARS_AFTER_PFLOW_6,
            e::VARS_AFTER_PFLOW_7,
            e::VARS_AFTER_PFLOW_8,
            e::VARS_AFTER_PFLOW_9,
            e::VARS_AFTER_PFLOW_10,
            e::VARS_AFTER_PFLOW_11,
            e::VARS_AFTER_PFLOW_12,
            e::VARS_AFTER_PFLOW_13,
            e::VARS_AFTER_PFLOW_14,
        ],
    );

    // S7: dynamics init (mode 14) with the converged pflow V/I
    dyn_rec.solution_mode = DYNAMICMODE;
    dyn_rec.h = H_DYN;
    mainunit::init(&mut state, &V_PF, &i_out, &mut gen);
    assert_bits("after_init_speed", gen.speed, e::AFTER_INIT_SPEED);

    // S8: three dynamics steps, predictor (flag 0) + corrector (flag 1)
    let dyn_i_expected: [[u64; 6]; 6] = [
        [
            e::DYN_I_1_0,
            e::DYN_I_1_1,
            e::DYN_I_1_2,
            e::DYN_I_1_3,
            e::DYN_I_1_4,
            e::DYN_I_1_5,
        ],
        [
            e::DYN_I_2_0,
            e::DYN_I_2_1,
            e::DYN_I_2_2,
            e::DYN_I_2_3,
            e::DYN_I_2_4,
            e::DYN_I_2_5,
        ],
        [
            e::DYN_I_3_0,
            e::DYN_I_3_1,
            e::DYN_I_3_2,
            e::DYN_I_3_3,
            e::DYN_I_3_4,
            e::DYN_I_3_5,
        ],
        [
            e::DYN_I_4_0,
            e::DYN_I_4_1,
            e::DYN_I_4_2,
            e::DYN_I_4_3,
            e::DYN_I_4_4,
            e::DYN_I_4_5,
        ],
        [
            e::DYN_I_5_0,
            e::DYN_I_5_1,
            e::DYN_I_5_2,
            e::DYN_I_5_3,
            e::DYN_I_5_4,
            e::DYN_I_5_5,
        ],
        [
            e::DYN_I_6_0,
            e::DYN_I_6_1,
            e::DYN_I_6_2,
            e::DYN_I_6_3,
            e::DYN_I_6_4,
            e::DYN_I_6_5,
        ],
    ];
    let dyn_slip_expected = [
        e::DYN_SLIP_1,
        e::DYN_SLIP_2,
        e::DYN_SLIP_3,
        e::DYN_SLIP_4,
        e::DYN_SLIP_5,
        e::DYN_SLIP_6,
    ];
    let mut n = 0;
    for _step in 0..3 {
        for flag in [0, 1] {
            dyn_rec.iteration_flag = flag;
            let wrote = mainunit::calc(&mut state, &V_DYN, &mut i_out, &mut gen, &dyn_rec);
            assert!(wrote);
            for k in 0..3 {
                assert_bits(
                    &format!("dyn_i_{}_{}", n + 1, 2 * k),
                    i_out[k].re,
                    dyn_i_expected[n][2 * k],
                );
                assert_bits(
                    &format!("dyn_i_{}_{}", n + 1, 2 * k + 1),
                    i_out[k].im,
                    dyn_i_expected[n][2 * k + 1],
                );
            }
            assert_bits(
                &format!("dyn_slip_{}", n + 1),
                mainunit::get_variable(&state, 1),
                dyn_slip_expected[n],
            );
            mainunit::integrate(&mut state, &gen, &dyn_rec);
            n += 1;
        }
    }

    // S9: variables after dynamics
    assert_vars(
        "vars_after_dyn",
        &vars(&state),
        &[
            e::VARS_AFTER_DYN_1,
            e::VARS_AFTER_DYN_2,
            e::VARS_AFTER_DYN_3,
            e::VARS_AFTER_DYN_4,
            e::VARS_AFTER_DYN_5,
            e::VARS_AFTER_DYN_6,
            e::VARS_AFTER_DYN_7,
            e::VARS_AFTER_DYN_8,
            e::VARS_AFTER_DYN_9,
            e::VARS_AFTER_DYN_10,
            e::VARS_AFTER_DYN_11,
            e::VARS_AFTER_DYN_12,
            e::VARS_AFTER_DYN_13,
            e::VARS_AFTER_DYN_14,
        ],
    );

    // S10: SetVariable(1) writes slip + generator speed
    mainunit::set_variable(&mut state, 1, -0.01, &mut gen);
    assert_bits("after_setvar_speed", gen.speed, e::AFTER_SETVAR_SPEED);
    assert_bits(
        "after_setvar_slip",
        mainunit::get_variable(&state, 1),
        e::AFTER_SETVAR_SLIP,
    );

    // S11: GetAllVars
    let mut all = [0.0f64; 14];
    mainunit::get_all_vars(&state, &mut all);
    assert_vars(
        "all_vars",
        &all,
        &[
            e::ALL_VARS_1,
            e::ALL_VARS_2,
            e::ALL_VARS_3,
            e::ALL_VARS_4,
            e::ALL_VARS_5,
            e::ALL_VARS_6,
            e::ALL_VARS_7,
            e::ALL_VARS_8,
            e::ALL_VARS_9,
            e::ALL_VARS_10,
            e::ALL_VARS_11,
            e::ALL_VARS_12,
            e::ALL_VARS_13,
            e::ALL_VARS_14,
        ],
    );

    // S12: Select out-of-range / in-range
    assert_eq!(mainunit::select(&mut state, 2), e::SELECT_2);
    assert_eq!(mainunit::select(&mut state, 1), e::SELECT_1);

    // S13: help (MsgCallBack) — also recalcs the element data
    mainunit::edit(&mut state, b"help", &mut gen, &mut sink);
    assert_eq!(msgs.len() as i32, e::HELP_MSG_COUNT);
    assert_eq!(std::str::from_utf8(&msgs[0]).unwrap(), e::HELP_MSG);
    assert_vars(
        "vars_after_help",
        &vars(&state),
        &[
            e::VARS_AFTER_HELP_1,
            e::VARS_AFTER_HELP_2,
            e::VARS_AFTER_HELP_3,
            e::VARS_AFTER_HELP_4,
            e::VARS_AFTER_HELP_5,
            e::VARS_AFTER_HELP_6,
            e::VARS_AFTER_HELP_7,
            e::VARS_AFTER_HELP_8,
            e::VARS_AFTER_HELP_9,
            e::VARS_AFTER_HELP_10,
            e::VARS_AFTER_HELP_11,
            e::VARS_AFTER_HELP_12,
            e::VARS_AFTER_HELP_13,
            e::VARS_AFTER_HELP_14,
        ],
    );

    // S14: second instance, delete, reselect
    let mut gen2 = GeneratorVars {
        w0: W0,
        kva_rating: 1000.0,
        kv_generator_base: 0.48,
        pnominal_per_phase: 300000.0,
        num_phases: 3,
        num_conductors: 3,
        conn: 1,
        ..Default::default()
    };
    let id2 = mainunit::new_instance(&mut state, &mut gen2, 0, 0);
    assert_eq!(id2, e::NEW2_ID);
    assert_bits("after_new2_speed", gen2.speed, e::AFTER_NEW2_SPEED);
    assert_bits("new2_slip", mainunit::get_variable(&state, 1), e::NEW2_SLIP);
    mainunit::delete(&mut state, 2);
    assert_eq!(mainunit::select(&mut state, 1), e::SELECT_1_AFTER_DELETE);
    assert_bits(
        "model1_purs",
        mainunit::get_variable(&state, 2),
        e::MODEL1_PURS,
    );
}

/// The V/I record-shuttle codec round-trips at the frozen offsets (a cheap
/// self-check of `records.rs` against hand-built images; the layout itself is
/// probe-frozen in the ABI doc).
#[test]
fn record_codec_round_trip() {
    use indmach012a::records::{
        decode_dynamics_rec, decode_generator_vars, encode_generator_vars, read_complex,
        write_complex, DYNAMICS_REC_SIZE, GENERATOR_VARS_SIZE,
    };

    let mut img = vec![0u8; GENERATOR_VARS_SIZE];
    // Hand-place a few sentinels at the frozen offsets.
    img[16..24].copy_from_slice(&2.5f64.to_le_bytes()); // Speed @16
    img[72..80].copy_from_slice(&0.48f64.to_le_bytes()); // kVGeneratorBase @72
    img[176..180].copy_from_slice(&3i32.to_le_bytes()); // NumPhases @176
    img[188..196].copy_from_slice(&7.75f64.to_le_bytes()); // VthevMag @188 (unaligned tail)
    img[236..244].copy_from_slice(&1.25f64.to_le_bytes()); // XRdp @236
    let gv = decode_generator_vars(&img);
    assert_eq!(gv.speed, 2.5);
    assert_eq!(gv.kv_generator_base, 0.48);
    assert_eq!(gv.num_phases, 3);
    assert_eq!(gv.vthev_mag, 7.75);
    assert_eq!(gv.xrdp, 1.25);
    let mut img2 = vec![0u8; GENERATOR_VARS_SIZE];
    encode_generator_vars(&gv, &mut img2);
    assert_eq!(img, img2, "GeneratorVars encode/decode round trip");

    let mut dimg = vec![0u8; DYNAMICS_REC_SIZE];
    dimg[0..8].copy_from_slice(&0.0002f64.to_le_bytes()); // h @0
    dimg[32..36].copy_from_slice(&1i32.to_le_bytes()); // IterationFlag @32
    dimg[36..40].copy_from_slice(&14i32.to_le_bytes()); // SolutionMode @36
    dimg[44..52].copy_from_slice(&0.5f64.to_le_bytes()); // dblHour @44
    let dr = decode_dynamics_rec(&dimg);
    assert_eq!(dr.h, 0.0002);
    assert_eq!(dr.iteration_flag, 1);
    assert_eq!(dr.solution_mode, 14);
    assert_eq!(dr.dbl_hour, 0.5);

    let mut cbuf = vec![0u8; 48];
    write_complex(&mut cbuf, 2, cmplx(1.5, -2.5));
    assert_eq!(read_complex(&cbuf, 2), cmplx(1.5, -2.5));
    assert_eq!(read_complex(&cbuf, 1), CZERO);
}
