//! Fixture self-gate (WP-WM.2 item 4): drives the COMMITTED
//! `tests/fixtures/wasm/indmach012a.wasm` through the `dss-usermodel` crate
//! API with hand-fed V/records and pins the computed currents / state
//! variables / record write-backs BIT-EXACT against the native twin (the FPC
//! build of the vendored `IndMach012a.dpr`, plan A) probed by
//! `tools/wasm_usermodel/twin_probe.py` — evidence
//! `docs/wasm/probes/p6_twin_expected.txt`, machine-readable copy
//! `tools/wasm_usermodel/models/indmach012a/tests/twin_expected.rs`
//! (generated by `twin_probe.py <dll> --rust`, included below verbatim).
//!
//! This is the whole chain the engine will use (WM.3): committed artifact →
//! `UserModelHost::load` export validation → `UserModelInstance` record
//! shuttle → guest math — so it catches guest-port math errors AND shuttle
//! marshalling errors before the engine integration exists. The model uses
//! only f64 `+ - * /` / `sqrt` (IEEE-exact in wasm and on x86-64 SSE2), so
//! the floor is exact bit equality — any mismatch is a bug, never tolerance
//! (`twin_parity.rs` pins the same scenario at the `mainunit` level; here the
//! committed binary + host plumbing are under test).
//!
//! Scenario coverage vs `twin_probe.py`: S1–S11 + S13 replayed 1:1. S12
//! (`select` of a foreign id) and S14 (two models in ONE guest) exercise
//! multi-model bookkeeping inside a single instance, which the crate API
//! deliberately does not expose — each `UserModelInstance` owns a fresh guest
//! (plan §2.7 per-element instances; Pascal gets multi-model state only
//! because one DLL is shared process-wide). The instance-level `select`
//! round-trip and a fresh-guest second instance are pinned instead.

use dss_usermodel::{
    DynamicsRec, Effect, GeneratorVars, HostConfig, InterfaceKind, NoCallbacks, Shuttle,
    UserModelHost, UserModelInstance,
};
use num_complex::Complex64;
use std::path::{Path, PathBuf};

/// The native-twin expected values (bit patterns), generated by
/// `twin_probe.py --rust` at WM.2 and committed with the fixture crate;
/// evidence copy `docs/wasm/probes/p6_twin_expected.txt`.
#[allow(dead_code)]
mod twin {
    include!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tools/wasm_usermodel/models/indmach012a/tests/twin_expected.rs"
    ));
}

// The fixed scenario inputs — duplicated verbatim from twin_probe.py.
const W0: f64 = 376.99111843077515; // 2*pi*60, fixed literal on both sides
const V_PF: [Complex64; 3] = [
    Complex64::new(277.13, 0.0),
    Complex64::new(-140.02, -239.51),
    Complex64::new(-137.11, 240.05),
];
const V_DYN: [Complex64; 3] = [
    Complex64::new(276.4, 3.1),
    Complex64::new(-141.0, -238.2),
    Complex64::new(-135.9, 239.9),
];
const EDIT_STR: &str =
    "rs=0.048 xs=0.075 rr=0.018 xr=0.12 Xm=3.8 maxs=0.1 option=variableslip slip=-0.02";
const H_DYN: f64 = 0.0002;
/// Pascal `TSolveMode` DYNAMICMODE = 14 (`Shared/Dynamics.pas`).
const DYNAMICMODE: i32 = 14;

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("..").join("..")
}

fn fixture_bytes() -> Vec<u8> {
    let path = repo_root()
        .join("tests")
        .join("fixtures")
        .join("wasm")
        .join("indmach012a.wasm");
    std::fs::read(&path).unwrap_or_else(|e| {
        panic!(
            "committed fixture must exist at {} (WM.2 item 2): {e}",
            path.display()
        )
    })
}

#[track_caller]
fn assert_bits(what: &str, got: f64, expected_bits: u64) {
    assert_eq!(
        got.to_bits(),
        expected_bits,
        "{what}: got {got:?} (0x{:016X}), twin has {:?} (0x{expected_bits:016X})",
        got.to_bits(),
        f64::from_bits(expected_bits),
    );
}

/// Fresh shuttle over the scenario's records (each call consumes one).
fn sh<'a>(gv: &'a mut GeneratorVars, dyn_rec: &'a mut DynamicsRec) -> Shuttle<'a> {
    Shuttle {
        gen_vars: Some(gv),
        dyn_rec,
        ctx: Box::new(NoCallbacks),
    }
}

/// Read all 14 user variables one by one (`get_variable`, 1-based).
fn vars(
    inst: &mut UserModelInstance,
    gv: &mut GeneratorVars,
    dyn_rec: &mut DynamicsRec,
) -> [f64; 14] {
    let mut out = [0.0f64; 14];
    for (i, slot) in out.iter_mut().enumerate() {
        *slot = inst
            .get_variable((i + 1) as i32, sh(gv, dyn_rec))
            .expect("get_variable");
    }
    out
}

#[track_caller]
fn assert_vars(prefix: &str, got: &[f64; 14], expected: &[u64; 14]) {
    for (i, (g, e)) in got.iter().zip(expected).enumerate() {
        assert_bits(&format!("{prefix}_{}", i + 1), *g, *e);
    }
}

/// The scenario's Generator record (twin_probe.py `make_genvars`).
fn scenario_genvars() -> GeneratorVars {
    GeneratorVars {
        w0: W0,
        hmass: 6.0,
        kva_rating: 1500.0,
        kv_generator_base: 0.48,
        pnominalperphase: 400000.0,
        qnominalperphase: 145000.0,
        num_phases: 3,
        num_conductors: 3,
        conn: 1,
        ..Default::default()
    }
}

/// Replay the twin scenario against `host`, pinning every recorded value.
fn run_twin_scenario(host: &UserModelHost) {
    use twin as e;

    let mut gv = scenario_genvars();
    let mut dyn_rec = DynamicsRec {
        h: 0.001,
        tstop: 1.0,
        solution_mode: 0, // SNAPSHOT
        ..Default::default()
    };

    // S1: New — id + the guest's slip→Speed write-back through the shuttle.
    let mut inst =
        UserModelInstance::new(host, 3, sh(&mut gv, &mut dyn_rec)).expect("instantiate + new");
    assert_eq!(inst.id(), e::NEW_ID);
    assert!(inst.exists());
    assert_bits("after_new_speed", gv.speed, e::AFTER_NEW_SPEED);

    // S2: variable-name surface (the crate scratch is 255 bytes; the
    // maxlen-truncation edge is pinned twin-side in twin_parity.rs).
    assert_eq!(
        inst.num_vars(sh(&mut gv, &mut dyn_rec)).expect("num_vars"),
        e::NUM_VARS
    );
    let expected_names: [&str; 14] = [
        e::VAR_NAME_1,
        e::VAR_NAME_2,
        e::VAR_NAME_3,
        e::VAR_NAME_4,
        e::VAR_NAME_5,
        e::VAR_NAME_6,
        e::VAR_NAME_7,
        e::VAR_NAME_8,
        e::VAR_NAME_9,
        e::VAR_NAME_10,
        e::VAR_NAME_11,
        e::VAR_NAME_12,
        e::VAR_NAME_13,
        e::VAR_NAME_14,
    ];
    for (i, want) in expected_names.iter().enumerate() {
        let name = inst
            .get_var_name((i + 1) as i32, sh(&mut gv, &mut dyn_rec))
            .expect("get_var_name");
        assert_eq!(name, *want, "var_name_{}", i + 1);
    }

    // S3: initial variables (post-Create state).
    assert_vars(
        "vars_initial",
        &vars(&mut inst, &mut gv, &mut dyn_rec),
        &[
            e::VARS_INITIAL_1,
            e::VARS_INITIAL_2,
            e::VARS_INITIAL_3,
            e::VARS_INITIAL_4,
            e::VARS_INITIAL_5,
            e::VARS_INITIAL_6,
            e::VARS_INITIAL_7,
            e::VARS_INITIAL_8,
            e::VARS_INITIAL_9,
            e::VARS_INITIAL_10,
            e::VARS_INITIAL_11,
            e::VARS_INITIAL_12,
            e::VARS_INITIAL_13,
            e::VARS_INITIAL_14,
        ],
    );

    // S4: Edit (the UserData= string) — slip→Speed write-back again.
    inst.edit(EDIT_STR, sh(&mut gv, &mut dyn_rec))
        .expect("edit");
    assert_bits("after_edit_speed", gv.speed, e::AFTER_EDIT_SPEED);
    assert_vars(
        "vars_after_edit",
        &vars(&mut inst, &mut gv, &mut dyn_rec),
        &[
            e::VARS_AFTER_EDIT_1,
            e::VARS_AFTER_EDIT_2,
            e::VARS_AFTER_EDIT_3,
            e::VARS_AFTER_EDIT_4,
            e::VARS_AFTER_EDIT_5,
            e::VARS_AFTER_EDIT_6,
            e::VARS_AFTER_EDIT_7,
            e::VARS_AFTER_EDIT_8,
            e::VARS_AFTER_EDIT_9,
            e::VARS_AFTER_EDIT_10,
            e::VARS_AFTER_EDIT_11,
            e::VARS_AFTER_EDIT_12,
            e::VARS_AFTER_EDIT_13,
            e::VARS_AFTER_EDIT_14,
        ],
    );

    // S5: five power-flow Calc iterations at fixed V (slip fixed-point).
    let pf_i_expected: [[u64; 6]; 5] = [
        [
            e::PF_I_1_0,
            e::PF_I_1_1,
            e::PF_I_1_2,
            e::PF_I_1_3,
            e::PF_I_1_4,
            e::PF_I_1_5,
        ],
        [
            e::PF_I_2_0,
            e::PF_I_2_1,
            e::PF_I_2_2,
            e::PF_I_2_3,
            e::PF_I_2_4,
            e::PF_I_2_5,
        ],
        [
            e::PF_I_3_0,
            e::PF_I_3_1,
            e::PF_I_3_2,
            e::PF_I_3_3,
            e::PF_I_3_4,
            e::PF_I_3_5,
        ],
        [
            e::PF_I_4_0,
            e::PF_I_4_1,
            e::PF_I_4_2,
            e::PF_I_4_3,
            e::PF_I_4_4,
            e::PF_I_4_5,
        ],
        [
            e::PF_I_5_0,
            e::PF_I_5_1,
            e::PF_I_5_2,
            e::PF_I_5_3,
            e::PF_I_5_4,
            e::PF_I_5_5,
        ],
    ];
    let pf_slip_expected = [
        e::PF_SLIP_1,
        e::PF_SLIP_2,
        e::PF_SLIP_3,
        e::PF_SLIP_4,
        e::PF_SLIP_5,
    ];
    let mut i_out = [Complex64::ZERO; 3];
    for it in 0..5 {
        inst.calc(&V_PF, &mut i_out, sh(&mut gv, &mut dyn_rec))
            .expect("pflow calc");
        for k in 0..3 {
            assert_bits(
                &format!("pf_i_{}_{}", it + 1, 2 * k),
                i_out[k].re,
                pf_i_expected[it][2 * k],
            );
            assert_bits(
                &format!("pf_i_{}_{}", it + 1, 2 * k + 1),
                i_out[k].im,
                pf_i_expected[it][2 * k + 1],
            );
        }
        assert_bits(
            &format!("pf_slip_{}", it + 1),
            inst.get_variable(1, sh(&mut gv, &mut dyn_rec))
                .expect("get_variable slip"),
            pf_slip_expected[it],
        );
    }

    // S6: variables after power flow.
    assert_vars(
        "vars_after_pflow",
        &vars(&mut inst, &mut gv, &mut dyn_rec),
        &[
            e::VARS_AFTER_PFLOW_1,
            e::VARS_AFTER_PFLOW_2,
            e::VARS_AFTER_PFLOW_3,
            e::VARS_AFTER_PFLOW_4,
            e::VARS_AFTER_PFLOW_5,
            e::VARS_AFTER_PFLOW_6,
            e::VARS_AFTER_PFLOW_7,
            e::VARS_AFTER_PFLOW_8,
            e::VARS_AFTER_PFLOW_9,
            e::VARS_AFTER_PFLOW_10,
            e::VARS_AFTER_PFLOW_11,
            e::VARS_AFTER_PFLOW_12,
            e::VARS_AFTER_PFLOW_13,
            e::VARS_AFTER_PFLOW_14,
        ],
    );

    // S7: dynamics init (mode 14) with the converged pflow V/I.
    dyn_rec.solution_mode = DYNAMICMODE;
    dyn_rec.h = H_DYN;
    let mut i_init = i_out;
    inst.init(&V_PF, &mut i_init, sh(&mut gv, &mut dyn_rec))
        .expect("init");
    assert_bits("after_init_speed", gv.speed, e::AFTER_INIT_SPEED);

    // S8: three dynamics steps, predictor (flag 0) + corrector (flag 1).
    let dyn_i_expected: [[u64; 6]; 6] = [
        [
            e::DYN_I_1_0,
            e::DYN_I_1_1,
            e::DYN_I_1_2,
            e::DYN_I_1_3,
            e::DYN_I_1_4,
            e::DYN_I_1_5,
        ],
        [
            e::DYN_I_2_0,
            e::DYN_I_2_1,
            e::DYN_I_2_2,
            e::DYN_I_2_3,
            e::DYN_I_2_4,
            e::DYN_I_2_5,
        ],
        [
            e::DYN_I_3_0,
            e::DYN_I_3_1,
            e::DYN_I_3_2,
            e::DYN_I_3_3,
            e::DYN_I_3_4,
            e::DYN_I_3_5,
        ],
        [
            e::DYN_I_4_0,
            e::DYN_I_4_1,
            e::DYN_I_4_2,
            e::DYN_I_4_3,
            e::DYN_I_4_4,
            e::DYN_I_4_5,
        ],
        [
            e::DYN_I_5_0,
            e::DYN_I_5_1,
            e::DYN_I_5_2,
            e::DYN_I_5_3,
            e::DYN_I_5_4,
            e::DYN_I_5_5,
        ],
        [
            e::DYN_I_6_0,
            e::DYN_I_6_1,
            e::DYN_I_6_2,
            e::DYN_I_6_3,
            e::DYN_I_6_4,
            e::DYN_I_6_5,
        ],
    ];
    let dyn_slip_expected = [
        e::DYN_SLIP_1,
        e::DYN_SLIP_2,
        e::DYN_SLIP_3,
        e::DYN_SLIP_4,
        e::DYN_SLIP_5,
        e::DYN_SLIP_6,
    ];
    let mut n = 0;
    for _step in 0..3 {
        for flag in [0, 1] {
            dyn_rec.iteration_flag = flag;
            inst.calc(&V_DYN, &mut i_out, sh(&mut gv, &mut dyn_rec))
                .expect("dyn calc");
            for k in 0..3 {
                assert_bits(
                    &format!("dyn_i_{}_{}", n + 1, 2 * k),
                    i_out[k].re,
                    dyn_i_expected[n][2 * k],
                );
                assert_bits(
                    &format!("dyn_i_{}_{}", n + 1, 2 * k + 1),
                    i_out[k].im,
                    dyn_i_expected[n][2 * k + 1],
                );
            }
            assert_bits(
                &format!("dyn_slip_{}", n + 1),
                inst.get_variable(1, sh(&mut gv, &mut dyn_rec))
                    .expect("get_variable slip"),
                dyn_slip_expected[n],
            );
            // Crate `integrate` = guest `select(id)` + `integrate` (the
            // Pascal wrapper, GenUserModel.pas:123-127).
            inst.integrate(sh(&mut gv, &mut dyn_rec))
                .expect("integrate");
            n += 1;
        }
    }

    // S9: variables after dynamics.
    assert_vars(
        "vars_after_dyn",
        &vars(&mut inst, &mut gv, &mut dyn_rec),
        &[
            e::VARS_AFTER_DYN_1,
            e::VARS_AFTER_DYN_2,
            e::VARS_AFTER_DYN_3,
            e::VARS_AFTER_DYN_4,
            e::VARS_AFTER_DYN_5,
            e::VARS_AFTER_DYN_6,
            e::VARS_AFTER_DYN_7,
            e::VARS_AFTER_DYN_8,
            e::VARS_AFTER_DYN_9,
            e::VARS_AFTER_DYN_10,
            e::VARS_AFTER_DYN_11,
            e::VARS_AFTER_DYN_12,
            e::VARS_AFTER_DYN_13,
            e::VARS_AFTER_DYN_14,
        ],
    );

    // S10: SetVariable(1) writes slip + the generator Speed write-back.
    inst.set_variable(1, -0.01, sh(&mut gv, &mut dyn_rec))
        .expect("set_variable");
    assert_bits("after_setvar_speed", gv.speed, e::AFTER_SETVAR_SPEED);
    assert_bits(
        "after_setvar_slip",
        inst.get_variable(1, sh(&mut gv, &mut dyn_rec))
            .expect("get_variable slip"),
        e::AFTER_SETVAR_SLIP,
    );

    // S11: GetAllVars (1-based semantics through the vars buffer).
    let mut all = [0.0f64; 14];
    inst.get_all_vars(&mut all, sh(&mut gv, &mut dyn_rec))
        .expect("get_all_vars");
    assert_vars(
        "all_vars",
        &all,
        &[
            e::ALL_VARS_1,
            e::ALL_VARS_2,
            e::ALL_VARS_3,
            e::ALL_VARS_4,
            e::ALL_VARS_5,
            e::ALL_VARS_6,
            e::ALL_VARS_7,
            e::ALL_VARS_8,
            e::ALL_VARS_9,
            e::ALL_VARS_10,
            e::ALL_VARS_11,
            e::ALL_VARS_12,
            e::ALL_VARS_13,
            e::ALL_VARS_14,
        ],
    );

    // S12 (crate-level form): the instance selects its own id round-trip.
    assert_eq!(
        inst.select(sh(&mut gv, &mut dyn_rec)).expect("select"),
        e::SELECT_1
    );

    // S13: `help` routes the twin's MsgCallBack text through the `dss_env`
    // msg_callback import into the tier-B effect queue — byte-identical.
    assert!(
        inst.drain_effects().is_empty(),
        "no effects queued before help"
    );
    inst.edit("help", sh(&mut gv, &mut dyn_rec))
        .expect("edit help");
    let effects = inst.drain_effects();
    assert_eq!(effects.len() as i32, e::HELP_MSG_COUNT);
    assert_eq!(effects, vec![Effect::Msg(e::HELP_MSG.to_string())]);
    assert_vars(
        "vars_after_help",
        &vars(&mut inst, &mut gv, &mut dyn_rec),
        &[
            e::VARS_AFTER_HELP_1,
            e::VARS_AFTER_HELP_2,
            e::VARS_AFTER_HELP_3,
            e::VARS_AFTER_HELP_4,
            e::VARS_AFTER_HELP_5,
            e::VARS_AFTER_HELP_6,
            e::VARS_AFTER_HELP_7,
            e::VARS_AFTER_HELP_8,
            e::VARS_AFTER_HELP_9,
            e::VARS_AFTER_HELP_10,
            e::VARS_AFTER_HELP_11,
            e::VARS_AFTER_HELP_12,
            e::VARS_AFTER_HELP_13,
            e::VARS_AFTER_HELP_14,
        ],
    );

    // S14 (crate-level form): a second element binding = a FRESH guest
    // instance (plan §2.7 — per-element `Store`, no shared ModelList), so its
    // id is 1 again; the twin's id2=2 belongs to the single shared native
    // DLL. The twin's post-Create pins (speed write-back, initial slip)
    // still apply verbatim.
    let mut gen2 = GeneratorVars {
        w0: W0,
        kva_rating: 1000.0,
        kv_generator_base: 0.48,
        pnominalperphase: 300000.0,
        num_phases: 3,
        num_conductors: 3,
        conn: 1,
        ..Default::default()
    };
    let mut dyn2 = DynamicsRec {
        h: 0.001,
        tstop: 1.0,
        solution_mode: 0,
        ..Default::default()
    };
    let mut inst2 =
        UserModelInstance::new(host, 3, sh(&mut gen2, &mut dyn2)).expect("second instance");
    assert_eq!(inst2.id(), 1, "fresh guest per instance (plan §2.7)");
    assert_bits("after_new2_speed", gen2.speed, e::AFTER_NEW2_SPEED);
    assert_bits(
        "new2_slip",
        inst2
            .get_variable(1, sh(&mut gen2, &mut dyn2))
            .expect("get_variable"),
        e::NEW2_SLIP,
    );
    inst2.delete(sh(&mut gen2, &mut dyn2)).expect("delete");
    assert!(!inst2.exists(), "delete clears the id");

    // The first instance is untouched by the second guest.
    assert_bits(
        "model1_purs",
        inst.get_variable(2, sh(&mut gv, &mut dyn_rec))
            .expect("get_variable puRs"),
        e::MODEL1_PURS,
    );
}

/// The self-gate proper: committed fixture + default sandbox limits.
#[test]
fn committed_fixture_matches_native_twin_bit_exact() {
    let host = UserModelHost::load(
        "indmach012a.wasm",
        &fixture_bytes(),
        InterfaceKind::GenUserModel,
        HostConfig::default(),
    )
    .expect("committed fixture loads + export set validates (Gen15)");
    run_twin_scenario(&host);
}

/// Fuel-calibration bar (plan §2.1 / WM.1 follow-up): every call of the
/// reference model must use <1% of the default per-call budget. Proven by
/// running the ENTIRE twin scenario (instantiation included) under a budget
/// of exactly 1% of `HostConfig::DEFAULT_FUEL_PER_CALL` — any call needing
/// more would abort as the loud `FuelExhausted` error.
#[test]
fn reference_model_calls_use_less_than_one_percent_of_default_fuel() {
    let config = HostConfig {
        fuel_per_call: HostConfig::DEFAULT_FUEL_PER_CALL / 100,
        ..Default::default()
    };
    let host = UserModelHost::load(
        "indmach012a.wasm",
        &fixture_bytes(),
        InterfaceKind::GenUserModel,
        config,
    )
    .expect("fixture loads under the calibration config");
    run_twin_scenario(&host);
}
