//! Phase 5 time-series/control gate (PHASE5_PLAN.md WP5.9): replay the
//! command-script scenarios of `tests/golden/phase5.json` (generated by
//! `tools/golden/gen_phase5.py` with the pinned oracle) and match
//!
//! - per-step `dblHour` exactly; per-step iteration counts exactly on the
//!   first step and within ±1 afterwards (see the in-line comment on why a
//!   tolerance-terminated fixed point cannot pin them bitwise across solvers),
//! - per-step node voltages at the scenario tolerance,
//! - final transformer taps (1e-12 rel — see the feeder gate for why not
//!   bitwise), RegControl tap numbers and capacitor states exactly,
//! - the event log normalized per line (numeric-skeleton comparison) — this
//!   pins every control action of the trajectory exactly.

mod harness;

use std::collections::BTreeMap;
use std::path::PathBuf;

use dss_core::exec::Dss;
use harness::{assert_complex_close, assert_value_matches_tol};
use serde::Deserialize;

#[derive(Debug, Deserialize)]
struct Phase5Golden {
    schema: u32,
    scenarios: Vec<Scenario>,
}

#[derive(Debug, Deserialize)]
struct Scenario {
    name: String,
    tol: f64,
    commands: Vec<String>,
    n_steps: usize,
    node_order: Vec<String>,
    steps: Vec<Step>,
    transformers: BTreeMap<String, Vec<f64>>,
    regcontrols: BTreeMap<String, i32>,
    capacitors: BTreeMap<String, Vec<i32>>,
    event_log: Vec<String>,
}

#[derive(Debug, Deserialize)]
struct Step {
    dbl_hour: f64,
    iterations: i32,
    converged: bool,
    v_re: Vec<f64>,
    v_im: Vec<f64>,
}

fn load_golden() -> Phase5Golden {
    let path: PathBuf = [
        env!("CARGO_MANIFEST_DIR"),
        "..",
        "..",
        "tests",
        "golden",
        "phase5.json",
    ]
    .iter()
    .collect();
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));
    let g: Phase5Golden = serde_json::from_str(&text)
        .unwrap_or_else(|e| panic!("cannot parse {}: {e}", path.display()));
    assert_eq!(g.schema, 1, "phase5 golden schema mismatch");
    g
}

fn run_scenario(sc: &Scenario) {
    let mut dss = Dss::new();
    dss.command("clear");
    for cmd in &sc.commands {
        dss.command(cmd);
    }
    assert!(
        dss.errors().is_empty(),
        "{}: unexpected engine errors: {:?}",
        sc.name,
        dss.errors()
    );

    assert_eq!(sc.steps.len(), sc.n_steps, "{}: malformed golden", sc.name);
    // Sticky: once a step's iteration count diverged (see below), that step
    // and every later one carry a convergence-tolerance-level (1e-4) offset
    // that does not shrink back — later steps re-converge to *their own*
    // 1e-4 stopping criterion from an already-offset start.
    let mut drifted = false;
    for (i, step) in sc.steps.iter().enumerate() {
        dss.command("solve");
        assert!(
            dss.errors().is_empty(),
            "{} step {i}: engine errors: {:?}",
            sc.name,
            dss.errors()
        );
        let ckt = dss.circuit().expect("circuit exists");
        assert!(
            step.converged,
            "{} step {i}: oracle did not converge",
            sc.name
        );
        assert!(ckt.is_solved, "{} step {i}: Rust did not converge", sc.name);
        assert!(
            (ckt.solution.dbl_hour - step.dbl_hour).abs() < 1e-12,
            "{} step {i}: dblHour {} vs {}",
            sc.name,
            ckt.solution.dbl_hour,
            step.dbl_hour
        );
        // Per-step iteration counts: exact on the first step (clean start —
        // the snapshot gates pin this), within ±1 on later steps. Each step's
        // fixed-point loop stops at the 1e-4 convergence tolerance, so when
        // the accumulated ~1e-6 trajectory drift (different sparse solver)
        // lands a step's max-error within noise of the threshold, one engine
        // takes one extra iteration. The *control* trajectory (every tap
        // change, with its control iteration, via the event log) stays exact.
        let iter_diff = (ckt.solution.iteration - step.iterations).abs();
        if i == 0 {
            assert_eq!(
                ckt.solution.iteration, step.iterations,
                "{} step {i}: iteration count differs",
                sc.name
            );
        } else {
            assert!(
                iter_diff <= 1,
                "{} step {i}: iteration count differs by more than 1: {} vs {}",
                sc.name,
                ckt.solution.iteration,
                step.iterations
            );
        }

        // Node order is captured once (it cannot change between steps).
        let names: Vec<String> = (1..=ckt.num_nodes).map(|i| ckt.node_name(i)).collect();
        assert_eq!(names, sc.node_order, "{} step {i}: node order", sc.name);

        let mut actual = Vec::with_capacity(2 * ckt.num_nodes);
        for n in 1..=ckt.num_nodes {
            actual.push(ckt.solution.node_v[n].re);
            actual.push(ckt.solution.node_v[n].im);
        }
        let mut expected = Vec::with_capacity(actual.len());
        for (re, im) in step.v_re.iter().zip(&step.v_im) {
            expected.push(*re);
            expected.push(*im);
        }
        // When the iteration counts have differed (this step or earlier), the
        // converged voltages legitimately differ by up to the last
        // iteration's increment — bounded by the 1e-4 convergence tolerance.
        drifted = drifted || iter_diff != 0;
        let vtol = if drifted { 2e-4 } else { sc.tol };
        assert_complex_close(
            &actual,
            &expected,
            vtol,
            1e-9,
            &format!("{} step {i} node voltages", sc.name),
        );
    }

    // Final control state.
    let taps = dss.transformer_taps();
    assert_eq!(
        taps.len(),
        sc.transformers.len(),
        "{}: transformer count",
        sc.name
    );
    for (tr_name, tr_taps) in &taps {
        let exp = &sc.transformers[tr_name];
        assert_eq!(tr_taps.len(), exp.len(), "{}: {tr_name} windings", sc.name);
        for (w, (a, e)) in tr_taps.iter().zip(exp).enumerate() {
            assert!(
                (a - e).abs() <= 1e-12 * e.abs().max(1.0),
                "{}: transformer {tr_name} winding {} tap: {a} vs {e}",
                sc.name,
                w + 1
            );
        }
    }
    let tap_numbers = dss.regcontrol_tap_numbers();
    assert_eq!(
        tap_numbers.len(),
        sc.regcontrols.len(),
        "{}: regcontrol count",
        sc.name
    );
    for (rc_name, tap_number) in &tap_numbers {
        assert_eq!(
            *tap_number, sc.regcontrols[rc_name],
            "{}: regcontrol {rc_name} tap number",
            sc.name
        );
    }
    let states = dss.capacitor_states();
    assert_eq!(
        states.len(),
        sc.capacitors.len(),
        "{}: capacitor count",
        sc.name
    );
    for (cap_name, cap_states) in &states {
        assert_eq!(
            cap_states, &sc.capacitors[cap_name],
            "{}: capacitor {cap_name} states",
            sc.name
        );
    }

    // Event log: normalized per-line equality (numbers at 1e-6 rel — tap
    // values inside event strings count as numbers).
    let log = dss.event_log();
    assert_eq!(
        log.len(),
        sc.event_log.len(),
        "{}: event log length differs:\n  actual:\n    {}\n  expected:\n    {}",
        sc.name,
        log.join("\n    "),
        sc.event_log.join("\n    ")
    );
    for (i, (a, e)) in log.iter().zip(&sc.event_log).enumerate() {
        assert_value_matches_tol(a, e, 1e-6, 1e-9, &format!("{} event-log line {i}", sc.name));
    }
}

#[test]
fn phase5_scenarios_match_oracle() {
    let golden = load_golden();
    assert_eq!(golden.scenarios.len(), 4, "expected 4 phase5 scenarios");
    for sc in &golden.scenarios {
        run_scenario(sc);
    }
}
