//! WP6.6 reliability gate: replay the feeders of `tests/golden/reliability.json`
//! (generated by `tools/golden/gen_reliability.py` with the pinned oracle) and
//! match the per-bus reliability quantities the backward/forward fault-rate
//! sweep populates before the `#52902` abort:
//!
//!   Bus.Lambda      = bus_flt_rate
//!   Bus.N_Customers = bus_total_num_customers
//!   Bus.TotalMiles  = bus_total_miles
//!   Bus.SectionID   = bus_section_id
//!
//! These are the reliability values the dss-python COM API *does* expose; the
//! per-branch accumulators (`AccumulatedBrFltRate`, `BranchSectionID`) have no
//! oracle getter and are pinned by the unit tests in `exec` instead.

use std::path::PathBuf;

use dss_core::exec::Dss;
use serde::Deserialize;

#[derive(Debug, Deserialize)]
struct ReliabilityGolden {
    schema: u32,
    scenarios: Vec<Scenario>,
}

#[derive(Debug, Deserialize)]
struct Scenario {
    name: String,
    commands: Vec<String>,
    relcalc_arg: String,
    /// The Pascal `DoSimpleMsg` error number the oracle raised (52902 = no OCP
    /// device). The Rust port surfaces the message text rather than the number.
    error_number: Option<i32>,
    buses: Vec<BusExpect>,
}

#[derive(Debug, Deserialize)]
struct BusExpect {
    name: String,
    #[serde(rename = "lambda")]
    lambda: f64,
    n_customers: i32,
    total_miles: f64,
    section_id: i32,
}

fn load_golden() -> ReliabilityGolden {
    let path: PathBuf = [
        env!("CARGO_MANIFEST_DIR"),
        "..",
        "..",
        "tests",
        "golden",
        "reliability.json",
    ]
    .iter()
    .collect();
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));
    let g: ReliabilityGolden = serde_json::from_str(&text)
        .unwrap_or_else(|e| panic!("cannot parse {}: {e}", path.display()));
    assert_eq!(g.schema, 1, "reliability golden schema mismatch");
    g
}

fn close(a: f64, e: f64) -> bool {
    (a - e).abs() <= 1e-9 + 1e-9 * e.abs()
}

fn run_scenario(sc: &Scenario) {
    let mut dss = Dss::new();
    dss.command("clear");
    for cmd in &sc.commands {
        dss.command(cmd);
    }
    assert!(
        dss.errors().is_empty(),
        "{}: unexpected build/solve errors: {:?}",
        sc.name,
        dss.errors()
    );

    let cmd = if sc.relcalc_arg.is_empty() {
        "Relcalc".to_string()
    } else {
        format!("Relcalc {}", sc.relcalc_arg)
    };
    dss.command(&cmd);

    // The oracle raised #52902 (no OCP device); the Rust port records the
    // equivalent message and aborts the indices, but the bus sweep still ran.
    if sc.error_number == Some(52902) {
        assert!(
            dss.errors().iter().any(|m| m
                .contains("No Overcurrent Protection device (Relay, Recloser, or Fuse) defined")),
            "{}: expected the #52902 abort message, got {:?}",
            sc.name,
            dss.errors()
        );
    }

    let ckt = dss.circuit().expect("circuit exists");
    for b in &sc.buses {
        let idx = ckt
            .bus_list
            .find(&b.name)
            .unwrap_or_else(|| panic!("{}: bus {} not found", sc.name, b.name));
        let bus = &ckt.buses[idx];
        assert!(
            close(bus.bus_flt_rate, b.lambda),
            "{}: bus {} Lambda {} vs oracle {}",
            sc.name,
            b.name,
            bus.bus_flt_rate,
            b.lambda
        );
        assert_eq!(
            bus.bus_total_num_customers, b.n_customers,
            "{}: bus {} N_Customers",
            sc.name, b.name
        );
        assert!(
            close(bus.bus_total_miles, b.total_miles),
            "{}: bus {} TotalMiles {} vs oracle {}",
            sc.name,
            b.name,
            bus.bus_total_miles,
            b.total_miles
        );
        assert_eq!(
            bus.bus_section_id, b.section_id,
            "{}: bus {} SectionID",
            sc.name, b.name
        );
    }
}

#[test]
fn reliability_bus_indices_match_oracle() {
    let golden = load_golden();
    assert_eq!(
        golden.scenarios.len(),
        2,
        "expected 2 reliability scenarios"
    );
    for sc in &golden.scenarios {
        run_scenario(sc);
    }
}
