//! WP-PF.1 `Pstcalc` command gate: replay `tests/golden/pstcalc/cmd_results.json`
//! (generated by `tools/golden/gen_pstcalc.py` with the pinned oracle) and match
//! the `GlobalResult` (`Text.Result`) string each `Pstcalc` command produces —
//! the `Format('%.8g, ')` list of per-10-minute-interval Pst values — **byte for
//! byte**.
//!
//! The matrix spans npts {12 (0 intervals -> empty), 700 (1), 1900 (3)}, a
//! modulated-sine and a repeated-step voltage shape, lamp {120, 230}, freq
//! {60, 50}, and a `dt` sweep (incl. a fractional dt exercising the FPC banker's
//! `Round` in `CyclesPerSample = Round(Solution.Frequency * dt)`). A mismatched
//! FPC `power`, `Round`, `%.8g` or filter-cascade interpretation fails the exact
//! compare. The npts<=10 guard case pins the #28723 error text (upstream typo
//! "Insuffient" verbatim).

use std::path::PathBuf;

use dss_core::exec::Dss;
use serde::Deserialize;

#[derive(Debug, Deserialize)]
struct PstGolden {
    schema: u32,
    cases: Vec<Case>,
}

#[derive(Debug, Deserialize)]
struct Case {
    name: String,
    commands: Vec<String>,
    /// The oracle `GlobalResult` after the `Pstcalc` command (empty for the
    /// 0-interval and error cases).
    result: String,
    /// The oracle `DSSException` message if the command raised one (the npts<=10
    /// guard), else `None`.
    error_message: Option<String>,
}

fn load_golden() -> PstGolden {
    let path: PathBuf = [
        env!("CARGO_MANIFEST_DIR"),
        "..",
        "..",
        "tests",
        "golden",
        "pstcalc",
        "cmd_results.json",
    ]
    .iter()
    .collect();
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));
    let g: PstGolden = serde_json::from_str(&text)
        .unwrap_or_else(|e| panic!("cannot parse {}: {e}", path.display()));
    assert_eq!(g.schema, 1, "pstcalc golden schema mismatch");
    g
}

fn run_case(c: &Case) {
    let mut dss = Dss::new();
    // Every command except the final `Pstcalc` is the fixed preamble and must
    // run cleanly.
    let (last, preamble) = c.commands.split_last().expect("at least one command");
    for cmd in preamble {
        dss.command(cmd);
    }
    assert!(
        dss.errors().is_empty(),
        "{}: unexpected preamble errors: {:?}",
        c.name,
        dss.errors()
    );

    dss.command(last);

    match &c.error_message {
        Some(msg) => {
            // The npts<=10 guard. The oracle wraps the text as "(#28723) <text>";
            // the Rust engine records the bare <text>. Assert the shared text and
            // that no result string was produced (both engines: empty).
            let text = msg.split_once(") ").map(|(_, t)| t).unwrap_or(msg.as_str());
            assert!(
                dss.errors().iter().any(|e| e.contains(text)),
                "{}: expected error text {text:?}, got {:?}",
                c.name,
                dss.errors()
            );
            assert_eq!(
                dss.result(),
                c.result,
                "{}: error-case result must match oracle (empty)",
                c.name
            );
        }
        None => {
            assert!(
                dss.errors().is_empty(),
                "{}: unexpected Pstcalc errors: {:?}",
                c.name,
                dss.errors()
            );
            // Byte-exact GlobalResult.
            assert_eq!(
                dss.result(),
                c.result,
                "{}: Pstcalc GlobalResult mismatch (Rust != oracle)",
                c.name
            );
        }
    }
}

#[test]
fn pstcalc_command_results_match_oracle_byte_exact() {
    let golden = load_golden();
    assert_eq!(golden.cases.len(), 25, "expected 25 pstcalc golden cases");
    for c in &golden.cases {
        run_case(c);
    }
}
