//! WP6.7 load-allocation gate: replay the feeders of
//! `tests/golden/allocation.json` (generated by `tools/golden/gen_allocation.py`
//! with the pinned oracle) and match, per load, the allocated quantities the
//! EnergyMeter/Sensor allocation loop produces after `allocateloads`:
//!
//!   Loads.kW               = kw_base
//!   Loads.AllocationFactor = allocation_factor
//!
//! Covers every allocation path — 3-phase ConnectedkVA, kWh/Cfactor spec,
//! unbalanced single-phase (distinct per-phase `PhsAllocationFactor`), a
//! current-spec Sensor and a P/Q Sensor driving a downstream load, plus
//! `NumAllocIterations`.

use std::path::PathBuf;

use dss_core::exec::Dss;
use serde::Deserialize;

#[derive(Debug, Deserialize)]
struct AllocationGolden {
    schema: u32,
    scenarios: Vec<Scenario>,
}

#[derive(Debug, Deserialize)]
struct Scenario {
    name: String,
    commands: Vec<String>,
    /// The Pascal `DoSimpleMsg` error number, if `allocateloads` raised one.
    /// Every ported scenario runs cleanly, so this is `None` throughout.
    error_number: Option<i32>,
    loads: Vec<LoadExpect>,
}

#[derive(Debug, Deserialize)]
struct LoadExpect {
    name: String,
    kw: f64,
    allocation_factor: f64,
}

fn load_golden() -> AllocationGolden {
    let path: PathBuf = [
        env!("CARGO_MANIFEST_DIR"),
        "..",
        "..",
        "tests",
        "golden",
        "allocation.json",
    ]
    .iter()
    .collect();
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));
    let g: AllocationGolden = serde_json::from_str(&text)
        .unwrap_or_else(|e| panic!("cannot parse {}: {e}", path.display()));
    assert_eq!(g.schema, 1, "allocation golden schema mismatch");
    g
}

fn close(a: f64, e: f64) -> bool {
    (a - e).abs() <= 1e-6 + 1e-7 * e.abs()
}

fn run_scenario(sc: &Scenario) {
    let mut dss = Dss::new();
    dss.command("clear");
    for cmd in &sc.commands {
        dss.command(cmd);
    }
    assert!(
        dss.errors().is_empty(),
        "{}: unexpected build/solve errors: {:?}",
        sc.name,
        dss.errors()
    );

    dss.command("allocateloads");
    assert_eq!(
        sc.error_number, None,
        "{}: golden recorded an allocateloads error #{:?}",
        sc.name, sc.error_number
    );
    assert!(
        dss.errors().is_empty(),
        "{}: unexpected allocateloads errors: {:?}",
        sc.name,
        dss.errors()
    );

    for l in &sc.loads {
        let (kw, factor) = dss
            .load_alloc(&l.name)
            .unwrap_or_else(|| panic!("{}: load {} not found", sc.name, l.name));
        assert!(
            close(kw, l.kw),
            "{}: load {} kW {kw} vs oracle {}",
            sc.name,
            l.name,
            l.kw
        );
        assert!(
            close(factor, l.allocation_factor),
            "{}: load {} AllocationFactor {factor} vs oracle {}",
            sc.name,
            l.name,
            l.allocation_factor
        );
    }
}

#[test]
fn allocation_loads_match_oracle() {
    let golden = load_golden();
    assert_eq!(golden.scenarios.len(), 6, "expected 6 allocation scenarios");
    for sc in &golden.scenarios {
        run_scenario(sc);
    }
}
