//! WP6.8 GenDispatcher gate: replay the scenarios of
//! `tests/golden/gendispatcher.json` (generated by
//! `tools/golden/gen_gendispatcher.py` with the pinned oracle) and match the
//! dispatched generator bases the snapshot control loop converges to:
//!
//!   Generators.kW   = Gen.kWBase
//!   Generators.kvar = Gen.kvarBase
//!
//! This pins the whole redispatch feedback path end to end (monitored-power read
//! → weighted PDiff/QDiff share → Max(1.0,…)/Max(0.0,…) floors → re-solve),
//! complementary to the per-arithmetic unit tests in
//! `elements::control::gen_dispatcher`. The control loop is a tolerance-
//! terminated fixed point, so the comparison uses the same 1e-6 tolerance as the
//! inline `exec` oracle tests rather than bitwise equality.

use std::path::PathBuf;

use dss_core::exec::Dss;
use serde::Deserialize;

#[derive(Debug, Deserialize)]
struct GenDispatcherGolden {
    schema: u32,
    scenarios: Vec<Scenario>,
}

#[derive(Debug, Deserialize)]
struct Scenario {
    name: String,
    commands: Vec<String>,
    generators: Vec<GenExpect>,
}

#[derive(Debug, Deserialize)]
struct GenExpect {
    name: String,
    kw: f64,
    kvar: f64,
}

fn load_golden() -> GenDispatcherGolden {
    let path: PathBuf = [
        env!("CARGO_MANIFEST_DIR"),
        "..",
        "..",
        "tests",
        "golden",
        "gendispatcher.json",
    ]
    .iter()
    .collect();
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));
    let g: GenDispatcherGolden = serde_json::from_str(&text)
        .unwrap_or_else(|e| panic!("cannot parse {}: {e}", path.display()));
    assert_eq!(g.schema, 1, "gendispatcher golden schema mismatch");
    g
}

fn close(a: f64, e: f64) -> bool {
    (a - e).abs() <= 1e-6 + 1e-6 * e.abs()
}

fn run_scenario(sc: &Scenario) {
    let mut dss = Dss::new();
    dss.command("clear");
    for cmd in &sc.commands {
        dss.command(cmd);
    }
    assert!(
        dss.errors().is_empty(),
        "{}: unexpected build/solve errors: {:?}",
        sc.name,
        dss.errors()
    );

    for g in &sc.generators {
        let (kw, kvar) = dss
            .generator_kw_kvar(&g.name)
            .unwrap_or_else(|| panic!("{}: generator {} not found", sc.name, g.name));
        assert!(
            close(kw, g.kw),
            "{}: generator {} kW {} vs oracle {}",
            sc.name,
            g.name,
            kw,
            g.kw
        );
        assert!(
            close(kvar, g.kvar),
            "{}: generator {} kvar {} vs oracle {}",
            sc.name,
            g.name,
            kvar,
            g.kvar
        );
    }
}

#[test]
fn gendispatcher_redispatch_matches_oracle() {
    let golden = load_golden();
    assert_eq!(
        golden.scenarios.len(),
        5,
        "expected 5 gendispatcher scenarios"
    );
    for sc in &golden.scenarios {
        run_scenario(sc);
    }
}
