//! Channel-1 hermetic replay gate for the WASM_USERMODELS **WM.5** CapControl
//! `UserModel=` user-control path (plan §2.5-1).
//!
//! The `tools/golden/wasm_decks/wasm_capcontrol.dss` deck is run on the **Rust**
//! engine with `@FIXTURE@` substituted by the committed `.wasm` fixture
//! (`tests/fixtures/wasm/capuserctl.wasm`), and the captured **switch-action
//! sequence** (event log), **final capacitor state** and **node voltages** are
//! compared against the committed golden
//! (`tests/golden/wasm_usermodels/wasm_capcontrol.json`).
//!
//! **Oracle = the r4133 built-in VOLTAGE CapControl, NOT a native twin.** WM.5
//! round 2 proved (from the r4133 source) that a native `TCapUserControl` DLL
//! cannot drive the r4133 control queue (the 7-fn `New` gives it no owning-element
//! pointer, and `ControlQueue.Push` needs the CapControl as `Owner` — see
//! `crates/dss-epri/tests/gen_wasm_usermodels_wm5.rs`). So the reference fixture's
//! deadband logic is made identical to the built-in VOLTAGE control
//! (OnSetting=vlow / OffSetting=vhigh) and the golden is generated by that
//! built-in control on the r4133 engine (`wasm_capcontrol_oracle.dss`). This is a
//! real cross-engine oracle comparison — Rust engine + wasm USERCONTROL fixture
//! vs the r4133 engine's independent built-in control — never "Rust agrees with
//! itself".
//!
//! The ONLY event-log difference is the built-in **Armed** rows (the shared
//! arm/disarm tail the direct-push USERCONTROL fixture bypasses, WM5-3); the gate
//! compares only the ordered SWITCH actions (**Opened**/**Closed**/**Step
//! Up/Down**), which are emitted identically by both `DoPendingAction` paths, plus
//! the final cap state and every node voltage at the harness floor.
//!
//! Hermetic (plan §2.6): needs only the committed `.wasm` + the committed golden —
//! no FPC, no native DLL, no wasm toolchain. Runs in every `cargo test`.

mod harness;

use std::collections::BTreeMap;

use dss_core::exec::Dss;
use harness::tol_for;
use serde::Deserialize;

/// The committed reference fixture, workspace-root-relative.
const FIXTURE_REL: &str = "tests/fixtures/wasm/capuserctl.wasm";

/// The committed r4133-oracle golden schema.
#[derive(Debug, Deserialize)]
struct WasmGolden {
    converged: bool,
    switch_actions: Vec<Vec<String>>,
    capacitor_states: BTreeMap<String, Vec<i32>>,
    node_voltages: BTreeMap<String, [f64; 2]>,
}

fn workspace_root() -> std::path::PathBuf {
    std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
}

fn load_golden() -> WasmGolden {
    let path = workspace_root().join("tests/golden/wasm_usermodels/wasm_capcontrol.json");
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("read golden {}: {e}", path.display()));
    serde_json::from_str(&text).unwrap_or_else(|e| panic!("parse golden {}: {e}", path.display()))
}

/// Parse the ordered SWITCH actions `(Element, Action)` from raw event-log lines
/// (`Hour=…, Element=…, Action=…`), keeping only the bank switches
/// (**Opened**/**Closed**/**Step Up**/**Step Down**) and dropping the
/// **Armed**/**Reset** queue-mechanism rows (the direct-push USERCONTROL path
/// omits them, WM5-3). Actions normalized to uppercase.
fn switch_actions(log: &[String]) -> Vec<(String, String)> {
    let mut out = Vec::new();
    for line in log {
        let (Some(elem), Some(action)) = (field(line, "Element="), field(line, "Action=")) else {
            continue;
        };
        let a = action.trim().to_ascii_uppercase();
        if a.starts_with("**OPENED**")
            || a.starts_with("**CLOSED**")
            || a.starts_with("**STEP UP**")
            || a.starts_with("**STEP DOWN**")
        {
            let label = a.split(',').next().unwrap_or(&a).trim().to_string();
            out.push((elem.trim().to_string(), label));
        }
    }
    out
}

fn field(line: &str, key: &str) -> Option<String> {
    let start = line.find(key)? + key.len();
    let rest = &line[start..];
    let end = rest.find(',').unwrap_or(rest.len());
    Some(rest[..end].to_string())
}

/// Parse a capacitor `states` dump `"[ 1 0 ...]"` into an i32 vector.
fn parse_states(dump: &str) -> Vec<i32> {
    dump.trim()
        .trim_start_matches('[')
        .trim_end_matches(']')
        .split_whitespace()
        .filter_map(|t| t.parse::<i32>().ok())
        .collect()
}

/// Run the WM.5 deck on the Rust engine with `@FIXTURE@` → the committed `.wasm`.
fn run_deck() -> Dss {
    let fixture = workspace_root()
        .join(FIXTURE_REL)
        .canonicalize()
        .unwrap_or_else(|e| panic!("canonicalize fixture: {e}"))
        .to_string_lossy()
        .trim_start_matches(r"\\?\")
        .replace('\\', "/");
    assert!(
        std::path::Path::new(&fixture).is_file(),
        "fixture missing: {fixture}"
    );
    let template = workspace_root().join("tools/golden/wasm_decks/wasm_capcontrol.dss");
    let text = std::fs::read_to_string(&template)
        .unwrap_or_else(|e| panic!("read deck {}: {e}", template.display()));
    // The deck quotes the path itself (`UserModel=@FIXTURE@` → the ABI IsFilename
    // path); substitute the bare absolute path.
    let deck_text = text.replace("@FIXTURE@", &format!("\"{fixture}\""));

    let mut dss = Dss::new();
    dss.command("clear");
    for line in deck_text.lines() {
        let t = line.trim();
        if t.is_empty() || t.starts_with('!') || t.starts_with("//") {
            continue;
        }
        dss.command(t);
    }
    dss
}

#[test]
fn wasm_capcontrol_matches_r4133_oracle() {
    let g = load_golden();
    let mut dss = run_deck();

    // The deck loads a real `.wasm`, so there is no "Not Loaded" warning and no
    // trap: the engine must be error-free (a surfaced user-model trap/protocol
    // fault would land here — plan §2.9-5, never a silent fallback).
    assert!(
        dss.errors().is_empty(),
        "unexpected engine errors: {:?}",
        dss.error_texts()
    );
    assert!(g.converged, "oracle golden did not converge");
    {
        let ckt = dss.circuit().expect("circuit built");
        assert!(ckt.is_solved, "Rust engine did not converge");
    }

    // --- Ordered switch-action sequence (event log) ---
    let rust_actions = switch_actions(dss.event_log());
    let oracle_actions: Vec<(String, String)> = g
        .switch_actions
        .iter()
        .map(|pair| (pair[0].clone(), pair[1].clone()))
        .collect();
    assert_eq!(
        rust_actions, oracle_actions,
        "switch-action sequence differs from the r4133 built-in-VOLTAGE oracle\n  rust:   \
         {rust_actions:?}\n  oracle: {oracle_actions:?}"
    );
    assert!(
        !rust_actions.is_empty(),
        "the deck must exercise at least one switch (guards against a silently \
         no-op USERCONTROL path)"
    );

    // --- Final capacitor state ---
    for (cap, states) in &g.capacitor_states {
        // `Capacitor.c` → `capacitor.c`.
        dss.command(&format!("? {}.states", cap.to_ascii_lowercase()));
        let got = parse_states(dss.result());
        assert_eq!(
            &got, states,
            "final state of {cap} differs (rust {got:?} vs oracle {states:?})"
        );
    }

    // --- Node voltages (by name, Y-node order) at the harness floor ---
    let vtol = tol_for("feeder");
    let names: Vec<String>;
    let volts: Vec<num_complex::Complex64>;
    {
        let ckt = dss.circuit().expect("circuit built");
        names = (1..=ckt.num_nodes).map(|j| ckt.node_name(j)).collect();
        volts = (1..=ckt.num_nodes)
            .map(|j| ckt.solution.node_v[j])
            .collect();
    }
    let actual_v: BTreeMap<String, num_complex::Complex64> = names
        .iter()
        .zip(&volts)
        .map(|(n, v)| (n.to_ascii_uppercase(), *v))
        .collect();

    let mut worst = 0.0_f64;
    let mut fails: Vec<String> = Vec::new();
    for (name, ev) in &g.node_voltages {
        let key = name.to_ascii_uppercase();
        let av = actual_v
            .get(&key)
            .unwrap_or_else(|| panic!("Rust missing node {name}"));
        for (label, actual, expected) in [
            (format!("V[{name}].re"), av.re, ev[0]),
            (format!("V[{name}].im"), av.im, ev[1]),
        ] {
            let diff = (actual - expected).abs();
            let allowed = vtol.v_abs + vtol.v_rel * expected.abs();
            if diff > allowed {
                fails.push(format!(
                    "{label}: rust {actual:.9e} vs oracle {expected:.9e} |diff|={diff:.3e} > {allowed:.3e}"
                ));
            }
            if expected.abs() > vtol.v_abs {
                worst = worst.max(diff / expected.abs());
            }
        }
    }
    eprintln!(
        "[wasm_usermodels_wm5] {} switches + {} caps + {} nodes @floor; worst rel = {worst:.3e}",
        oracle_actions.len(),
        g.capacitor_states.len(),
        g.node_voltages.len(),
    );
    assert!(
        fails.is_empty(),
        "{} node voltages out of tolerance (worst rel {worst:.3e}):\n  {}",
        fails.len(),
        fails.join("\n  ")
    );
}

/// `like=` must carry a **live** user control (RP1.3 audit settlement,
/// 2026-08-23). Pascal `MakeLike` does `UserModel.Name :=
/// OtherCapControl.UserModel.Name` (`CapControl.pas:452`), a `Set_Name` = eager
/// free + `LoadLibrary` + `FNew`; the port used to `clone()` the donor's slot,
/// whose `Clone` drops the live wasmi instance, so the copy kept
/// `IsUserModel = TRUE` (copied at `:453`) with nothing behind it — a
/// USERCONTROL that samples, decides nothing and switches nothing, silently.
///
/// The observable is the second bank: `cc2` watches the same node as `cc` with
/// the same deadband, so on the light-load step (V above `vhigh`) a live model
/// must OPEN `c2`, exactly as `cc` opens `c`. A dead slot leaves `c2` closed and
/// contributes no event-log action.
///
/// The deadband has to be re-sent: `Set_Name` gives the copy a **fresh** instance
/// at the guest's own defaults and Pascal never replays the donor's `UserData`
/// into it (`:459` copies the property array, which is only the `?` echo) — the
/// same law the WindGen `like=` pin documents. That `Edit` is itself part of the
/// discrimination: `Set_Edit` is `If FID <> 0 Then FEdit(…)`, so a dead slot
/// swallows it silently.
#[test]
fn like_carries_a_live_user_control() {
    let mut dss = run_deck();
    dss.command("new capacitor.c2 bus1=cbus phases=3 kv=12.47 kvar=1500");
    dss.command("new capcontrol.cc2 like=cc capacitor=c2");
    dss.command("edit capcontrol.cc2 UserData=\"node=4 vlow=7000 vhigh=7250\"");
    assert!(
        dss.errors().is_empty(),
        "`like=` must not error: {:?}",
        dss.error_texts()
    );
    // Light load again: the monitored node rises clear of `vhigh`, so every live
    // control opens its bank.
    dss.command("edit load.ld kw=500");
    dss.command("solve");

    dss.command("? capacitor.c.states");
    let c = parse_states(dss.result());
    dss.command("? capacitor.c2.states");
    let c2 = parse_states(dss.result());
    assert_eq!(c, vec![0], "the donor's control opened its own bank");
    assert_eq!(
        c2, c,
        "the `like=` copy must run a LIVE user control, not a dead slot"
    );
    assert!(
        switch_actions(dss.event_log())
            .iter()
            .any(|(elem, _)| elem.eq_ignore_ascii_case("Capacitor.c2")),
        "the copy must appear in the event log: {:?}",
        switch_actions(dss.event_log())
    );
}

/// The committed WM.5 golden parses and has the expected shape (guards against a
/// truncated / regenerated-from-Rust golden).
#[test]
fn wm5_golden_is_well_formed() {
    let g = load_golden();
    assert!(g.converged);
    assert_eq!(
        g.switch_actions,
        vec![
            vec!["Capacitor.c".to_string(), "**OPENED**".to_string()],
            vec!["Capacitor.c".to_string(), "**CLOSED**".to_string()],
        ],
        "WM.5 golden switch sequence changed"
    );
    assert_eq!(g.capacitor_states.get("Capacitor.c"), Some(&vec![1]));
    assert_eq!(
        g.node_voltages.len(),
        6,
        "expected 6 nodes (SRC+CBUS × 3ph)"
    );
}
